export const PREFERENCES_ACTIONS = {
  UPDATE_OCCURRED_EVENT: 'UPDATE_OCCURRED_EVENT',
}

export const OCCURRED_EVENTS = {
  CLIPART_SHOWCASE_CARD_DASHBOARD_DISMISSED: 'CLIPART_SHOWCASE_CARD_DASHBOARD_DISMISSED',
  GET_STARTED_CARD_DASHBOARD_DISMISSED: 'GET_STARTED_CARD_DASHBOARD_DISMISSED',
  PRODUCT_SUGGESTED_CARD_DASHBOARD_DISMISSED: 'PRODUCT_SUGGESTED_CARD_DASHBOARD_DISMISSED',
  AI_ONBOARDING_COMPLETED_VER_1: 'ai_onboarding_completed_ver_1',
  SETUP_GUIDE_CARD_DASHBOARD_DISMISSED: 'SETUP_GUIDE_CARD_DASHBOARD_DISMISSED',
  THANKS_FOR_YOUR_FEEDBACK_CARD_DASHBOARD_DISMISSED: 'THANKS_FOR_YOUR_FEEDBACK_CARD_DASHBOARD_DISMISSED',
  HOW_S_TAILORKIT_WORKING_FOR_YOU_CARD_DASHBOARD_DISMISSED: 'HOW_S_TAILORKIT_WORKING_FOR_YOU_CARD_DASHBOARD_DISMISSED',
  TRY_OUR_OTHER_APPS_CARD_DASHBOARD_DISMISSED: 'TRY_OUR_OTHER_APPS_CARD_DASHBOARD_DISMISSED',
  EXPLORE_OUR_BLOG_CARD_DASHBOARD_DISMISSED: 'EXPLORE_OUR_BLOG_CARD_DASHBOARD_DISMISSED',
  GET_STARTED_WITH_TAILORKIT_CARD_DASHBOARD_DISMISSED: 'GET_STARTED_WITH_TAILORKIT_CARD_DASHBOARD_DISMISSED',
  TUTORIALS_CARD_DASHBOARD_DISMISSED: 'TUTORIALS_CARD_DASHBOARD_DISMISSED',
  NEED_HELP_CARD_DASHBOARD_DISMISSED: 'NEED_HELP_CARD_DASHBOARD_DISMISSED',
  PUBLISH_TO_EARN_CARD_DASHBOARD_DISMISSED: 'PUBLISH_TO_EARN_CARD_DASHBOARD_DISMISSED',
  TRIAL_USAGE_CARD_DASHBOARD_DISMISSED: 'TRIAL_USAGE_CARD_DASHBOARD_DISMISSED',
  THEMES_PROMO_CARD_DASHBOARD_DISMISSED: 'THEMES_PROMO_CARD_DASHBOARD_DISMISSED',
  POST_PUBLISH_CHECKLIST_DISMISSED: 'POST_PUBLISH_CHECKLIST_DISMISSED',
}
