import { evaluateRequestForMutatingAssets } from '~/models/Asset.server'
import type { LayerDocument } from '~/models/Layer.server'
import Layer from '~/models/Layer.server'
import OptionSet from '~/models/OptionSet.server'
import PSD from '~/models/PSD.server'
import Template, { createTemplateOrClipart } from '~/models/Template.server'
import { duplicateLayers } from '~/modules/TemplateEditor/fns'
import type { NodeImage, Template as TTemplate } from '~/types/psd'
import { uuid } from '~/utils/uuid'
import { TEMPLATE_TYPE, isStoreAsset } from './constants'
import { fetchList } from '~/bootstrap/fns/fetch.server'
import type { LoaderFunctionArgs } from '@remix-run/node'
import { getClipartsDetailsBySelection } from '~/services/cliparts.server'
import ImageModel from '~/models/Image.server'
import { preparePreviewUpload, getCdnBaseUrl } from '~/routes/api.templates.$id/previewImage.server'
import type { OptionSetDocument } from '~/models/OptionSet'
import { DEFAULT_STORE_ASSET_DOMAIN } from '~/root'

/**
 * Core template duplication logic shared between different duplication functions
 * @param templateData - The template object to duplicate
 * @param targetShopDomain - The shop domain where the template will be created
 * @param templateOverrides - Optional overrides for the new template
 * @returns Object containing the new template information
 */
async function duplicateTemplateCore(
  templateData: TTemplate,
  targetShopDomain: string,
  templateOverrides: Partial<TTemplate> = {}
) {
  // Duplicate PSD data
  const psds: string[] = []
  for (const psd of templateData.psds || []) {
    const newPsd = await PSD.create({
      ...psd,
      _id: uuid(),
      shopDomain: targetShopDomain,
    })
    if (newPsd) {
      psds.push(newPsd._id)
    }
  }

  // Create mapping for image IDs (old ID -> new ID)
  const imageIdMapping: Record<string, string> = {}
  const images = (templateData.layers.map(l => l.image) as NodeImage[]).filter(Boolean) || []

  // Generate new IDs for all images
  images.forEach(image => {
    if (typeof image === 'string') {
      imageIdMapping[image] = uuid()
    }

    if (image?._id) {
      imageIdMapping[image._id] = uuid()
    }
  })

  // Duplicate layer data with new image ID references.
  // Do NOT pre-assign layer _id here — duplicateLayers builds its own layerMapping so that
  // conditionalLogic (thenShowOrHideLayers / isControlledBy) is correctly remapped to new IDs.
  // forceNewOptionSetIds ensures cloned layers get independent OptionSet documents,
  // preventing the original's OptionSets from being overwritten when the copy is saved.
  const layers = duplicateLayers({
    layers: (templateData.layers || []).map(l => {
      return {
        ...l,
        ...(l.type === 'image' && l.image
          ? {
              image: imageIdMapping[typeof l.image === 'string' ? l.image : (l.image as NodeImage)?._id],
            }
          : {}),
        createdAt: new Date(),
        updatedAt: new Date(),
      }
    }),
    shopDomain: targetShopDomain,
    forceNewOptionSetIds: true,
  })

  // Clone ALL option sets for every layer (both clipart and regular templates).
  // forceNewOptionSetIds in duplicateLayers already assigned fresh _ids to each option set object;
  // here we persist those new documents so the copy's layers reference independent OptionSet records
  // and saves on the copy cannot overwrite the original template's OptionSets.
  const allOptionSets = layers.flatMap(layer =>
    (layer.optionSet || []).map(os => ({
      ...(os as OptionSetDocument),
      shopDomain: targetShopDomain,
    }))
  )
  if (allOptionSets.length > 0) {
    await OptionSet.insertMany(allOptionSets)
  }

  // Insert layers
  await Layer.insertMany(
    layers.map((layer: LayerDocument) => ({
      ...layer,
      shopDomain: targetShopDomain,
      // Use the new option set IDs generated by duplicateLayers (forceNewOptionSetIds: true)
      optionSet: layer.optionSet ? layer.optionSet.map(os => (typeof os === 'string' ? os : os._id)) : undefined,
    }))
  )

  // Duplicate images
  await Promise.all(
    images.map(async image => {
      const imageId = typeof image === 'string' ? image : image._id
      const newImageId = imageIdMapping[imageId]
      const imageData = (typeof image === 'string' ? await ImageModel.findOne({ _id: imageId }).lean() : image) || {}

      // Remove Mongo/Mongoose internals and fields we explicitly control
      const {
        __v: _omitVersion,
        _id: _omitOldId,
        createdAt: _omitCreatedAt,
        updatedAt: _omitUpdatedAt,
        shopDomain: _omitShopDomain,
        ...sanitizedImageData
      } = imageData as any

      return ImageModel.updateOne(
        { _id: newImageId },
        {
          $set: {
            ...sanitizedImageData,
            shopDomain: targetShopDomain,
            updatedAt: new Date(),
          },
          $setOnInsert: {
            _id: newImageId,
            createdAt: new Date(),
          },
        },
        {
          upsert: true,
        }
      )
    })
  )

  // Generate a unique name for the template
  let max = 0
  const baseName = templateData.name || 'Template'

  const templatesHavingSameName = await Template.aggregate([
    {
      $match: {
        $and: [
          { shopDomain: targetShopDomain },
          { deletedAt: null },
          {
            name: {
              $regex: new RegExp(`^${baseName.replace(/ \(\d+\)$/, '')}( \\(\\d+\\))?$`),
            },
          },
        ],
      },
    },
  ])

  templatesHavingSameName.forEach(item => {
    const num = Number(item.name.replace(/^.+\((\d+)\)$/, '$1'))
    if (!isNaN(num) && num > max) {
      max = num
    }
  })

  // Handle metadata properly
  let processedMetadata = templateData.metadata
  if (typeof templateData.metadata?.templateDescription === 'string') {
    processedMetadata = {
      ...templateData.metadata,
      templateDescription: {
        content: templateData.metadata.templateDescription,
        createdAt: new Date(),
      },
    }
  }

  // Prepare template data for creation
  const {
    createdAt: _omitCreatedAt,
    updatedAt: _omitUpdatedAt,
    _id: _omitId,
    previewUrl: _omitPreviewUrl, // do not inherit original preview to avoid cross-deletion
    ...restTemplateData
  } = templateData

  // Generate a fresh preview for the duplicated template so it has its own asset
  let duplicatedPreviewUrl = ''
  let scheduleUpload: ((prev: any) => Promise<void>) | undefined
  try {
    const sourceUrl = (templateData as any).previewUrl as string | undefined
    if (sourceUrl) {
      const res = await fetch(sourceUrl)
      if (res.ok) {
        const mimeType = res.headers.get('content-type') || 'image/webp'
        const ab = await res.arrayBuffer()
        const blob = new Blob([ab], { type: mimeType })
        const { cdnUrl, uploadTask } = preparePreviewUpload(blob as unknown as File, targetShopDomain, getCdnBaseUrl())
        duplicatedPreviewUrl = cdnUrl
        scheduleUpload = uploadTask
      }
    }
  } catch (_) {
    // Ignore and proceed without preview if fetching/copying fails
  }

  const newTemplateId = uuid()
  // Perform the background upload without deleting the original's preview
  if (scheduleUpload) {
    try {
      // Pass a previousTemplate with empty previewUrl so deletion logic is skipped
      await scheduleUpload({ _id: newTemplateId, previewUrl: _omitPreviewUrl } as any)
    } catch (error) {
      console.warn('Failed to generate preview for duplicated template', error)
      duplicatedPreviewUrl = ''
    }
  }

  const newTemplateData = {
    ...restTemplateData,
    _id: newTemplateId,
    name: max > 0 ? `${baseName.replace(/ \(\d+\)$/, '')} (${max + 1})` : baseName,
    psds,
    layers: layers.map((layer: LayerDocument) => layer._id),
    activeVariantIntegration: [], // Reset integrations
    shopDomain: targetShopDomain,
    metadata: processedMetadata,
    previewUrl: duplicatedPreviewUrl,
    ...templateOverrides, // Apply any overrides
  }

  // Create the new template
  const result = await createTemplateOrClipart(targetShopDomain, newTemplateData)

  return {
    templateId: result.templateId,
    isFirstTemplate: result.isFirstTemplate,
    templateName: newTemplateData.name,
  }
}

export const duplicateTemplates = async (templates: string[] | TTemplate[], shopDomain: string) => {
  let _templatesData = []

  // Evaluate request number, with increase number equals to template length
  await evaluateRequestForMutatingAssets(shopDomain, templates.length)

  if (typeof templates[0] === 'string') {
    // Get template data
    _templatesData = await Template.find({ shopDomain, _id: { $in: templates } }).populate([
      {
        path: 'psds',
        model: PSD,
      },
      {
        path: 'layers',
        model: Layer,
        populate: [{ path: 'optionSet', model: OptionSet }],
      },
    ])
  } else {
    _templatesData = templates
  }

  for (let templateIdx = 0; templateIdx < _templatesData.length; templateIdx++) {
    const templateData = _templatesData[templateIdx].toObject()
    await duplicateTemplateCore(templateData, shopDomain)
  }
}

/**
 * Clone a clipart template to the user's own account as a regular template
 * @param clipartId - The ID of the clipart template to clone
 * @param targetShopDomain - The shop domain where the template will be cloned to
 * @returns The newly created template information
 */
export const cloneClipartToTemplate = async (clipartId: string, targetShopDomain: string) => {
  // Evaluate request for mutating assets
  await evaluateRequestForMutatingAssets(targetShopDomain, 1)

  // Fetch the original clipart template from the store asset domain
  const storeAssetDomain = process.env.STORE_ASSET_DOMAIN || DEFAULT_STORE_ASSET_DOMAIN

  if (!storeAssetDomain) {
    throw new Error('Store asset domain not configured')
  }

  // Get the clipart template details
  const [clipartTemplate] = await getClipartsDetailsBySelection(
    [{ _id: clipartId, type: TEMPLATE_TYPE.PREMADE_TEMPLATE }],
    storeAssetDomain
  )

  if (!clipartTemplate) {
    throw new Error('Clipart template not found')
  }

  // Verify it's actually from store asset domain
  if (!isStoreAsset(clipartTemplate.shopDomain)) {
    throw new Error('Template is not a clipart or premade template')
  }

  // Use shared duplication logic with clipart-specific overrides
  const templateOverrides = {
    type: TEMPLATE_TYPE.TEMPLATE, // Convert to regular template
    category: undefined, // Remove category to make it a personal template
  }

  const result = await duplicateTemplateCore(clipartTemplate, targetShopDomain, templateOverrides)

  return result
}

/**
 * Get list templates
 * @param request - The request object
 * @param shopDomain - The shop domain
 * @returns The list templates
 */
export const getListTemplates = async (request: LoaderFunctionArgs['request'], shopDomain?: string) => {
  const t1 = performance.now()
  // Get templates
  const { page, items, total } = await fetchList(
    request,
    Template,
    [
      {
        $match: {
          deletedAt: { $eq: null },
          type: { $ne: TEMPLATE_TYPE.CLIPART },
        },
      },
      {
        $project: {
          name: 1,
          metadata: 1,
          dimension: 1,
          createdAt: 1,
          updatedAt: 1,
          previewUrl: 1,
          shopDomain: 1,
          activeVariantIntegration: {
            $cond: {
              if: { $isArray: '$activeVariantIntegration' },
              then: '$activeVariantIntegration',
              else: [],
            },
          },
          status: {
            $cond: {
              if: { $isArray: '$activeVariantIntegration' },
              then: {
                $cond: {
                  if: { $gt: [{ $size: '$activeVariantIntegration' }, 0] },
                  then: 'active',
                  else: 'inactive',
                },
              },
              else: 'inactive',
            },
          },
        },
      },
    ],
    [],
    false,
    [],
    shopDomain
  )
  const t2 = performance.now()

  return { page, items, total, totalExecutionTimeInMs: t2 - t1 }
}
