export const IDB_STORE_NAME = {
  TEMPLATE_DIMENSION: 'IDB_TEMPLATE_DIMENSION_STORE_TAILORKIT',
  LAYER_SETTINGS: 'IDB_LAYER_SETTINGS_STORE_TAILORKIT',
  INTEGRATION: 'IDB_INTEGRATION_STORE_TAILORKIT',
  INTEGRATION_TEMPORARY: 'IDB_INTEGRATION_TEMPORARY_STORE_TAILORKIT',
  PSD_FILE: 'psd_file',
  TEMPORARY_PRODUCT_DATA: 'IDB_TEMPORARY_PRODUCT_DATA_STORE_TAILORKIT',
}

export const IDB_DATABASE_NAME = {
  PSD: 'IDB_PSD_DATABASE_TAILORKIT',
  TEMPLATE_DIMENSION: 'IDB_TEMPLATE_DIMENSION_DATABASE_TAILORKIT',
  VARIANTS_SELECTED: 'IDB_VARIANTS_SELECTED_DATABASE_TAILORKIT',
  LAYER_SETTINGS: 'IDB_LAYER_SETTINGS_DATABASE_TAILORKIT',
  INTEGRATION: 'IDB_INTEGRATION_DATABASE_TAILORKIT',
  TEMPLATE_SELECTED: 'IDB_TEMPLATE_SELECTED_DATABASE_TAILORKIT',
  TEMPORARY_PRODUCTS: 'IDB_TEMPORARY_PRODUCTS_DATABASE_TAILORKIT',
}
