export const TEMPLATE_NAME_MAX_LENGTH = 255
export const COMMON_WIDTH_VALUE = 500
export const COMMON_HEIGHT_VALUE = 500

/**
 * @description: Shopify restrict the properties size for each item is 1024 bytes
 * So we need to limit the input characters size for merchants/customers
 * At this time, practically 1 character for documentation is 2 bytes
 * => Maximum: 1024 / 2 = 512
 */
export const MAXIMUM_CHARACTER_UTF_16_COUNT = 512

const MAXIMUM_RANGE_FONT_SIZE = 999
const MINIMUM_RANGE_FONT_SIZE = 8
const DEFAULT_FONT_SIZE = 200

const MAXIMUM_FONT_SIZE = 999
const MINIMUM_FONT_SIZE = 8

const MAXIMUM_RANGE_STROKE_WEIGHT = 100
const MINIMUM_RANGE_STROKE_WEIGHT = 0

// Stroke weight is now percentage of fontSize (0-100%)
const MAXIMUM_STROKE_WEIGHT = 100
const MINIMUM_STROKE_WEIGHT = 0

const MAXIMUM_RANGE_LETTER_SPACING = 50
const MINIMUM_RANGE_LETTER_SPACING = 0
const DEFAULT_LETTER_SPACING = 0

const MAXIMUM_RANGE_LINE_HEIGHT = 10
const MINIMUM_RANGE_LINE_HEIGHT = 0.1

const MAXIMUM_NEON_OFFSET = 100
const MINIMUM_NEON_OFFSET = -100

export {
  MAXIMUM_RANGE_FONT_SIZE,
  MINIMUM_RANGE_FONT_SIZE,
  DEFAULT_FONT_SIZE,
  MAXIMUM_FONT_SIZE,
  MINIMUM_FONT_SIZE,
  MAXIMUM_RANGE_STROKE_WEIGHT,
  MINIMUM_RANGE_STROKE_WEIGHT,
  MAXIMUM_STROKE_WEIGHT,
  MINIMUM_STROKE_WEIGHT,
  MAXIMUM_RANGE_LETTER_SPACING,
  MINIMUM_RANGE_LETTER_SPACING,
  DEFAULT_LETTER_SPACING,
  MAXIMUM_RANGE_LINE_HEIGHT,
  MINIMUM_RANGE_LINE_HEIGHT,
  MAXIMUM_NEON_OFFSET,
  MINIMUM_NEON_OFFSET,
}
