export const productEditorSnapshotScaffoldPolicy = {
  mode: 'removed-from-runtime-tree',
  removedRoot: 'apps/tailorkit/src/admin/product-editor',
  deprecatedHost: 'apps/tailorkit/src/admin/product-editor-host.tsx',
  deprecatedHostExecutionMode: 'disabled-copy-first-only',
  replacementTarget: 'apps/tailorkit/upstream/tailorkit-app/app/modules/ProductEditor/index.tsx',
  removedFiles: [
    'apps/tailorkit/src/admin/product-editor/canvas-preview-model.ts',
    'apps/tailorkit/src/admin/product-editor/constants.ts',
    'apps/tailorkit/src/admin/product-editor/editor-canvas-shell.tsx',
    'apps/tailorkit/src/admin/product-editor/editor-draft-actions.ts',
    'apps/tailorkit/src/admin/product-editor/editor-draft-state.ts',
    'apps/tailorkit/src/admin/product-editor/editor-draft-store.ts',
    'apps/tailorkit/src/admin/product-editor/editor-inspector.tsx',
    'apps/tailorkit/src/admin/product-editor/editor-state-helpers.ts',
    'apps/tailorkit/src/admin/product-editor/layers-manager.tsx',
    'apps/tailorkit/src/admin/product-editor/mockup-views-manager.tsx',
    'apps/tailorkit/src/admin/product-editor/post-publish-checklist-panel.tsx',
    'apps/tailorkit/src/admin/product-editor/post-publish-checklist.ts',
    'apps/tailorkit/src/admin/product-editor/print-areas-manager.tsx',
    'apps/tailorkit/src/admin/product-editor/product-base-draft-reducer.ts',
    'apps/tailorkit/src/admin/product-editor/product-base-setting.tsx',
    'apps/tailorkit/src/admin/product-editor/product-base-variant-adapter.ts',
    'apps/tailorkit/src/admin/product-editor/product-editor-actions.ts',
    'apps/tailorkit/src/admin/product-editor/product-editor-draft-save-request.ts',
    'apps/tailorkit/src/admin/product-editor/product-editor-publish-readiness-modal.tsx',
    'apps/tailorkit/src/admin/product-editor/product-editor-save-bar.tsx',
    'apps/tailorkit/src/admin/product-editor/product-editor-unpublish-modal.tsx',
    'apps/tailorkit/src/admin/product-editor/product-editor.tsx',
    'apps/tailorkit/src/admin/product-editor/publish-snapshot-panel.tsx',
    'apps/tailorkit/src/admin/product-editor/resolve-product-preview-image.ts',
    'apps/tailorkit/src/admin/product-editor/save-payload-builder.ts',
    'apps/tailorkit/src/admin/product-editor/source-map.ts',
    'apps/tailorkit/src/admin/product-editor/status.ts',
    'apps/tailorkit/src/admin/product-editor/template-editor-adapter.ts',
    'apps/tailorkit/src/admin/product-editor/template-editor-state-adapter.ts',
    'apps/tailorkit/src/admin/product-editor/unified-header.tsx',
    'apps/tailorkit/src/admin/product-editor/use-product-editor-draft.ts',
  ],
} as const

export const productEditorFrozenSnapshotScaffoldFiles = [] as const
