/* eslint-disable max-len */
/**
 * Property prefix is serving for hiding meta data properties in cart
 * This will be replaced during build time
 */
export const PROPERTY_PREFIX = '_%{PROPERTY_PREFIX}%'

export enum EHtmlSelectors {
  ATC_BUTTON = 'form[action*="/cart/add"] button[type="submit"], form[action*="/cart/add"] button[name="add"], form[action*="/cart/add"] button[class="product-buy-buttons--cta"]',
  SECTION = '.shopify-section, div[data-pf-type="ProductBox"], product-info',
  CART_DRAWER = 'cart-drawer,#CartPopup,.cart-drawer,sht-cart-drwr,.cart__drawer,.drawer--cart,div[id="CartDrawer"],#CartDrawer,.quick-cart,sidebar-drawer,.mfp-cart-draw,.mini-cart,.mini_cart,cart-modal,aside,cart-root,cart-notification,aside[id="cart"],section.cart,.mini-cart-modal,cart-sidebar,#cartDrawer,.cart-side-drawer,.Cart-Drawer,section-cart-drawer,drawer-modal,.drawer,mini-cart,form[action="/checkout"],section[x-show="cart_drawer"],drawer-component,modal-component[data-modal="modal-cart-drawer"],loess-drawer[id="CartDrawer"],.sidebar-drawer-container,.side-cart,.topbar-content,.flyout,.dialog__content,cart-popup,.header-minicart,cart-items',
  CART_DRAWER_HEADER = 'cart-drawer header,.upcart-header, .cart-drawer header, sht-cart-drwr .drawer__header, cart-drawer .drawer__header, cart-drawer .drawer-header, cart-drawer .cart_header, .cart__drawer .drawer__header, .cart-drawer .drawer__header, .drawer--cart .drawer__header, div[id="CartDrawer"] .drawer__header, cart-drawer .cart-drawer__header, cart-drawer .f-drawer__header, .cart-drawer .cart-drawer__header, #CartDrawer .drawer__fixed-header, cart-drawer .cart-drawer__top, cart-drawer drawer__head, .quick-cart .quick-cart__header, .shopify-section .quick-cart__header, cart-drawer .mini-cart__header, .cart__drawer .drawer__top, .cart-drawer .cart-drawer__head, .cart-drawer .side-panel-header, sidebar-drawer .sidebar__header, .mfp-cart-draw .cart-draw__head, .mini-cart .ajax-cart__header-wrapper, .mini_cart .yv_side_drawer_title, cart-modal .modal-header, aside .cart-drawer__top, cart-root .cart--header, cart-notification .cart-notification__header, aside[id="cart"] header, section.cart .header, cart-drawer .drawer__heading, sidebar-drawer .site-cart-heading, .mini-cart-modal .mini-cart__heading-wrapper, cart-sidebar .cart-sidebar__header, .cart-drawer .cart__title, #cartDrawer .sd-sidebar-head, .cart-drawer .cart-drawer-content-header, .cart-side-drawer .cart-drawer-content-header, cart-drawer [class~="cart-drawer-header"], .Cart-Drawer .Drawer__Header, section-cart-drawer .Drawer__Header, drawer-modal .drawer-header, sidebar-drawer .cart__title, cart-drawer .modal-heading, .drawer .quick-cart__tabs, mini-cart .mini-cart-header, cart-notification .cart_notification_topbar, form[action="/checkout"] .mm-subtitle, section[x-show="cart_drawer"] section, drawer-component .mini-cart__close, body aside[id="cart"] header, cart-items [class~="cart-items-header"], sidebar-drawer .sidebar__close, modal-component[data-modal="modal-cart-drawer"] .modal-component_head, loess-drawer[id="CartDrawer"] header, .sidebar-drawer-container .sidebar-drawer__header-container, .side-cart .side-cart-header, aside .cart-header-details, .topbar-content .topbar-header, .flyout .flyout__header-wrapper, .dialog__content .main-cart__heading, cart-popup .popup__header, .header-minicart .header-minicart-header, mini-cart .minicart-top',
  CART_DRAWER_ITEMS = 'cart-drawer-items,.upcart-cart-body,cart-popup-items, .cart-drawer .cart-drawer__body ,.cart-drawer__content, sht-cart-drwr .drawer__body, .drawer__scrollable, .cart-drawer__inner, sidebar-drawer .sidebar__body, .cart-drawer .side-panel-content, cart-drawer .drawer__content, .cart-drawer .cart__table, cart-root .cart--body, .cart-drawer .cart-drawer__content, .quick-cart__items, .Cart-Drawer .Drawer__Main, drawer-modal .header-mini-cart-content, cart-drawer [class~="cart-drawer-products"], aside .cart-items, div[id="cart"] .cart-items, drawer-modal .drawer-content, .cart-drawer .cart-drawer__cart, cart-drawer .cart-drawer__blocks, .mini-cart .ajax-cart__cart-items, .mini-cart .mini-cart__content, section-cart-drawer .Drawer__Body, cart-notification .cart__items, .drawer--cart .ajaxcart__inner, .drawer .ajaxcart__inner, sidebar-drawer .cart__items, sidebar-drawer .cart-items, mini-cart .header-mini-cart-content, .cart-drawer .cart-drawer__section--items, cart-sidebar .cart-sidebar__items, mini-cart .cart-items-wrapper, .cart__drawer .cart__items, .cart-drawer .cart-drawer__items, loess-drawer .cart-form, aside .cart_list, .minicart-sidebar .minicart__box, .side-cart .items, .header-minicart-drawer .header-minicart-content, .drawer--cart .ajaxcart__product, cart-drawer .cart-drawer-cart-items-wrapper, .cart-drawer-form__contents, .main-mini-cart-items, .side-cart .side-cart-content, drawer .cart-drawer-form, aside[id="cart"] ul, cart-modal #CartModal-ScrollBody, .cart-drawer-content-body, #cart-drawer-live-region-products, .cart-mini-items, modal-component[data-modal="modal-cart-drawer"] .modal-component_content, mini-cart .mini-cart-item-list, cart-form',
  CART_DRAWER_FOOTER = '.drawer__footer, .cart-drawer footer, .cart-drawer bottom',
  INPUT_VARIANT_ID = 'input[name="id"]',
  SELECTOR_REPLACE = 'cart-items , cart-drawer , form[action="/cart"],a[href="/cart"],.cart__item ,.js-contents',
}

export enum EPubSubEvents {
  CART_UPDATE = 'cart-update',
  UPDATE_VARIANT_IN_CHECKBOX = 'update_variant',
  SELECTED_VARIANT_CHANGE = 'selected_variant_change',
  INJECT_PRODUCT_OFFER_INTO_CART_DRAWER = 'inject_product_product_offer_into_cart_drawer',

  REMOVE_DATA_INPUT_FORM = 'remove_data_input_form',
}
