import { ARRAY_SEPARATOR, FEEDBACK_TYPE } from './common'
import { GENERAL_FEEDBACK_FORM } from './general_feedback_form'
import { GIVE_USE_FEEDBACK_FORM } from './give_us_feedback_form'
import { INTEGRATION_FUNCTIONALITY_FORM } from './integration_functionality_form'
import { ONBOARDING_FORM, ONBOARDING_PRODUCT_YOUR_SELL_KEY, ONBOARDING_QUESTION_KEY } from './onboarding_forms'
import { OVERALL_EXPERIENCE_FORM } from './overall_experience_form'
import { PRINT_AREA_SETUP_AND_MANAGEMENT_FORM } from './print_area_setup_and_management_form'
import { PRODUCT_CATALOG_SUPPLIER_SELECTION_FORM } from './product_catalog_supplier_selection_form'
import { TEMPLATE_EDITOR_FUNCTIONALITY_FORM } from './template_editor_functionality_form'

const DEFAULT_FEEDBACK_ACTIVATOR_ID = 'feedback-form-activator'

export {
  FEEDBACK_TYPE,
  ARRAY_SEPARATOR,
  ONBOARDING_FORM,
  GIVE_USE_FEEDBACK_FORM,
  TEMPLATE_EDITOR_FUNCTIONALITY_FORM,
  INTEGRATION_FUNCTIONALITY_FORM,
  PRODUCT_CATALOG_SUPPLIER_SELECTION_FORM,
  PRINT_AREA_SETUP_AND_MANAGEMENT_FORM,
  OVERALL_EXPERIENCE_FORM,
  GENERAL_FEEDBACK_FORM,
  DEFAULT_FEEDBACK_ACTIVATOR_ID,
  ONBOARDING_QUESTION_KEY,
  ONBOARDING_PRODUCT_YOUR_SELL_KEY,
}
