export * from './layers'
export * from './templates'

const CUSTOM_MARKDOWN = '~~~'

export const MCP_TOOLS_EVENTS_MARKDOWN = {
  LOADING: `${CUSTOM_MARKDOWN}LOADING${CUSTOM_MARKDOWN}`,
  LOADING_DONE: `${CUSTOM_MARKDOWN}LOADING_DONE${CUSTOM_MARKDOWN}`,
  TEMPLATE_CREATED: `${CUSTOM_MARKDOWN}TEMPLATE_CREATED${CUSTOM_MARKDOWN}`,
  LAYER_CREATED_OR_UPDATED: `${CUSTOM_MARKDOWN}LAYER_CREATED_OR_UPDATED${CUSTOM_MARKDOWN}`,
  READ_COLLECTION_DATA: `${CUSTOM_MARKDOWN}READ_COLLECTION_DATA${CUSTOM_MARKDOWN}`,
}
