import type Konva from 'konva'
import { CANVAS_HEIGHT, CANVAS_WIDTH } from '~/constants/canvas'
import type { MEASUREMENT_UNIT } from '~/constants/measurement-units'
import type { Reducer } from '~/libs/external-store'
import { createStore } from '~/libs/external-store'
import { revaluateCanvasViewPort } from '~/utils/canvas/revaluateCanvasViewPort'
import { EOptionSet, ELayerType, type OptionSet, type CharmNodeSettings } from '~/types/psd'
import {
  getCharmLayerByInstanceId,
  unregisterCharmLayer,
  clearCharmLayerIndex,
} from '~/stores/modules/charm-layer-index'
import type { TemplateDimension, ViewPort } from '~/types/template'
import { lengthUnitToLengthUnit /*, resizeDimensionFromResolutionToResolution*/ } from '~/utils/lengthUnitToPixels'
import { getLayerStoreById, type TLayerStore } from './layer'
import { TEMPLATE_TYPE } from '~/routes/api.templates/constants'
import type { Step } from '~/libs/steps.client'
import { addSteps } from '~/libs/steps.client'
import { createRef } from 'react'
import { stepCallback } from './integration/fns'
import { getSaveBarId } from './template/get-save-bar-id'
import type { WizardConfig } from '~/types/wizard'

export const DEFAULT_TEMPLATE_DIMENSION: TemplateDimension = {
  width: CANVAS_WIDTH,
  height: CANVAS_HEIGHT,
  measurementUnit: 'px',
  resolution: 300,
}

type Trace = {
  skipTrace?: boolean
}

export type TemplateEditor = {
  _id: string
  /**
   * Name of the template.
   */
  name: string
  /**
   * Shop domain of the template.
   */
  shopDomain: string
  /**
   * Extracted layer stores of the template. These layers are representing on Outline.
   */
  extractedLayerStores: TLayerStore[]
  /**
   * Whether the template is extracting from PSD.
   */
  extracting: boolean
  /**
   * Viewport of the template.
   */
  viewport: ViewPort
  /**
   * Dimension of the template.
   */
  dimension: TemplateDimension
  /**
   * Whether the template is interactive. It's false in preview mode.
   */
  interactive: boolean
  /**
   * All option set list of the template.
   */
  allOptionSetList?: any
  /**
   * Type of the template.
   */
  type?: string
  /**
   * Cliparts added to the template.
   */
  clipartsAdded?: TemplateEditor[]
  /**
   * Category of the template. It can come from pre-made templates.
   */
  category?: string
  /**
   * Metadata of the template.
   */
  metadata?: {
    /**
     * Description of the template. This is generated by AI by default.
     */
    templateDescription?: {
      content: string
      createdAt: Date
    }
    /**
     * Whether the template is using AI feature.
     */
    generatedByAIAssistantAt?: string | Date
    /**
     * Whether to save thumbnail with preview product image.
     * Only applicable for store asset domain.
     */
    saveThumbnailWithPreview?: boolean
  }
  /**
   * Stage reference of the template.
   */
  stageRef?: React.RefObject<Konva.Stage> | null
  /**
   * Whether the sidebar is active.
   */
  sidebarActive?: boolean
  /**
   * Whether anchors are currently being dragged (for text shapes).
   */
  isAnchorDragging?: boolean
  /**
   * Preview URL of the template.
   */
  previewUrl?: string
  createdAt?: Date | string
  /**
   * Preview product image rendered on the canvas for UX guidance.
   */
  previewProductImage?: {
    _id?: string
    src: string
    altText?: string
    left: number
    top: number
    width: number
    height: number
    rotation: number
    naturalWidth?: number
    naturalHeight?: number
    /** Controls visibility on canvas without removing the data */
    visible?: boolean
  } | null
  /**
   * Whether the template is creating new.
   */
  isCreatingNew?: boolean
  /**
   * Active variant integration of the template.
   */
  activeVariantIntegration?: {
    _id: string
    productId: string
  }[]
  /**
   * Step-by-step wizard configuration for storefront personalization.
   * Saved with the template and published to metafields.
   */
  wizardConfig?: WizardConfig | null
}

type Action =
  | { type: 'SET_LOADING'; payload: { extracting: boolean } }
  | { type: 'INIT_DATA'; payload: { state: Partial<TemplateEditor> } }
  | { type: 'SET_TEMPLATE_GENERATED_DATA'; payload: { state: Partial<TemplateEditor> } }
  | { type: 'SET_NAME'; payload: { name: string } }
  | { type: 'SET_VIEW_PORT'; payload: { viewport: ViewPort } }
  | { type: 'SET_DIMENSION'; payload: { dimension: TemplateDimension } }
  | { type: 'SET_VIEW_PORT_AND_DIMENSION'; payload: { viewport: ViewPort; dimension: TemplateDimension } }
  | { type: 'SET_INTERACTIVE'; payload: { interactive: boolean } }
  | { type: 'SET_MEASUREMENT_UNIT'; payload: { fromUnit: MEASUREMENT_UNIT; toUnit: MEASUREMENT_UNIT } }
  | {
      type: 'SET_RESOLUTION'
      payload: { toResolution: TemplateDimension['resolution'] }
    }
  | { type: 'ADD_EXTRACTED_LAYER_IDS'; payload: { extractedLayerStores: TLayerStore[] } }
  | { type: 'DELETE_EXTRACTED_LAYER_IDS'; payload: { extractedLayerStores: TLayerStore[] } }
  | { type: 'SET_EXTRACTED_LAYER_IDS'; payload: { extractedLayerStores: TLayerStore[] } }
  | { type: 'SET_OPTION_SET_LISTS'; payload: { optionSetLists: OptionSet[] } }
  | { type: 'UPDATE_OPTION_SET_LISTS'; payload: { type: string; optionUpdatedLists: OptionSet[] } }
  | { type: 'SET_CLIPARTS'; payload: { extractedLayerStores?: any[]; clipartsAdded: TemplateEditor[] } }
  | { type: 'SET_CATEGORY'; payload: { category?: string } }
  | { type: 'SET_STAGE_REF'; payload: { stageRef: React.RefObject<Konva.Stage> | null } }
  | { type: 'SET_SIDEBAR_ACTIVE'; payload: { sidebarActive: boolean } }
  | { type: 'SET_ANCHOR_DRAGGING'; payload: { isAnchorDragging: boolean } }
  | {
      type: 'SET_PREVIEW_PRODUCT_IMAGE'
      payload: {
        previewProductImage:
          | TemplateEditor['previewProductImage']
          | Partial<NonNullable<TemplateEditor['previewProductImage']>>
        merge?: boolean
      }
    }
  | { type: 'SET_METADATA_SAVE_THUMBNAIL_WITH_PREVIEW'; payload: { saveThumbnailWithPreview: boolean } }
  | { type: 'RESET_STATE' }

export const DEFAULT_TEMPLATE_EDITOR_STORE: TemplateEditor = {
  _id: '',
  shopDomain: '',
  name: 'Untitled',
  extractedLayerStores: [],
  extracting: false,
  dimension: DEFAULT_TEMPLATE_DIMENSION,
  viewport: {
    scale: 1,
    left: 0,
    top: 0,
  },
  interactive: false,
  allOptionSetList: {
    [EOptionSet.TEXT_OPTION]: [],
    [EOptionSet.IMAGE_OPTION]: [],
    [EOptionSet.COLOR_OPTION]: [],
    [EOptionSet.FONT_OPTION]: [],
    [EOptionSet.MASK_OPTION]: [],
  },
  type: TEMPLATE_TYPE.TEMPLATE,
  clipartsAdded: [],
  stageRef: createRef<Konva.Stage>(),
  sidebarActive: true,
  isAnchorDragging: false,
  previewProductImage: null,
}

const templateEditorReducer: Reducer<TemplateEditor, Action> = (state, action) => {
  switch (action.type) {
    case 'SET_LOADING': {
      const payload = action.payload
      return {
        ...state,
        extracting: payload.extracting,
      }
    }

    case 'SET_TEMPLATE_GENERATED_DATA':
    case 'INIT_DATA': {
      const payload = action.payload

      return {
        ...state,
        ...(payload.state || payload),
      }
    }

    case 'SET_NAME': {
      const payload = action.payload

      const name = payload.name
      return {
        ...state,
        // Only input words, numbers and space
        name: name,
      }
    }

    case 'SET_VIEW_PORT': {
      const payload = action.payload

      const viewport = payload.viewport
      return {
        ...state,
        viewport,
      }
    }

    case 'SET_DIMENSION': {
      const payload = action.payload

      const { width, height, measurementUnit, resolution } = payload.dimension

      const _dimension = { width, height, measurementUnit, resolution }

      const viewport = revaluateCanvasViewPort(_dimension)

      return {
        ...state,
        dimension: _dimension,
        viewport,
      }
    }

    case 'SET_VIEW_PORT_AND_DIMENSION': {
      const payload = action.payload

      const { viewport, dimension } = payload

      return {
        ...state,
        dimension,
        viewport,
      }
    }

    case 'SET_INTERACTIVE': {
      const { interactive } = action.payload

      return {
        ...state,
        interactive,
      }
    }

    case 'SET_MEASUREMENT_UNIT': {
      const payload = action.payload

      const { fromUnit, toUnit } = payload
      const dimension = state.dimension

      if (!dimension) {
        return {
          ...state,
        }
      }

      const { width, height, resolution } = dimension

      const _width = lengthUnitToLengthUnit(fromUnit, toUnit, width, resolution)
      const _height = lengthUnitToLengthUnit(fromUnit, toUnit, height, resolution)

      const _dimension = { width: _width, height: _height, measurementUnit: toUnit, resolution }

      const viewport = revaluateCanvasViewPort(_dimension)

      return {
        ...state,
        dimension: _dimension,
        viewport,
      }
    }

    case 'SET_RESOLUTION': {
      const payload = action.payload

      const { toResolution } = payload
      const dimension = state.dimension

      if (!dimension) {
        return {
          ...state,
        }
      }

      const { width, height, /*resolution,*/ measurementUnit } = dimension

      /* Re-evaluate the width & height
      const _width = resizeDimensionFromResolutionToResolution(
        resolution,
        toResolution,
        width,
        dimension.measurementUnit
      )

      const _height = resizeDimensionFromResolutionToResolution(
        resolution,
        toResolution,
        height,
        dimension.measurementUnit
      )*/

      const _dimension = { width /*: _width*/, height /*: _height*/, resolution: toResolution, measurementUnit }

      const viewport = revaluateCanvasViewPort(_dimension)

      return {
        ...state,
        dimension: _dimension,
        viewport,
      }
    }

    case 'ADD_EXTRACTED_LAYER_IDS': {
      const payload = action.payload

      return {
        ...state,
        extractedLayerStores: [...payload.extractedLayerStores, ...state.extractedLayerStores],
      }
    }

    case 'DELETE_EXTRACTED_LAYER_IDS': {
      const payload = action.payload

      const deletedExtractedLayerStores = payload.extractedLayerStores

      return {
        ...state,
        // Exclude the layer stores out of the state extractedLayerStores
        extractedLayerStores: state.extractedLayerStores.filter(
          layerStore =>
            !deletedExtractedLayerStores
              .map(deletedLayerStore => deletedLayerStore.getState()._id)
              .includes(layerStore.getState()._id)
        ),
      }
    }

    case 'SET_CLIPARTS': {
      const payload = action.payload

      return {
        ...state,
        ...payload,

        /** @deprecated Previous is ADD_CLIPARTS */
        // extractedLayerStores: [...extractedLayerStores, ...state.extractedLayerStores],
      }
    }

    case 'SET_EXTRACTED_LAYER_IDS': {
      const payload = action.payload

      return {
        ...state,
        extractedLayerStores: payload.extractedLayerStores,
      }
    }

    case 'SET_STAGE_REF': {
      const payload = action.payload

      return {
        ...state,
        stageRef: payload.stageRef,
      }
    }

    case 'SET_SIDEBAR_ACTIVE': {
      const payload = action.payload

      return {
        ...state,
        sidebarActive: payload.sidebarActive,
      }
    }

    case 'SET_PREVIEW_PRODUCT_IMAGE': {
      const { previewProductImage, merge } = action.payload
      // If merge requested and both current and incoming are objects, merge; else replace (including null to clear)
      const nextPreview
        = merge && state.previewProductImage && previewProductImage && typeof previewProductImage === 'object'
          ? { ...state.previewProductImage, ...previewProductImage }
          : (previewProductImage as TemplateEditor['previewProductImage'])

      return {
        ...state,
        previewProductImage: nextPreview ?? null,
      }
    }

    case 'RESET_STATE':
      return DEFAULT_TEMPLATE_EDITOR_STORE

    case 'SET_OPTION_SET_LISTS':
      const payload = action.payload
      const { TEXT_OPTION, IMAGE_OPTION, COLOR_OPTION, FONT_OPTION, MASK_OPTION } = EOptionSet
      const allOptionSetListsDefault: any = {
        [TEXT_OPTION]: [],
        [IMAGE_OPTION]: [],
        [COLOR_OPTION]: [],
        [FONT_OPTION]: [],
        [MASK_OPTION]: [],
      }

      const allOptionSetList = payload.optionSetLists.reduce((acc, option) => {
        if (acc[option.type]) {
          acc[option.type].push(option)
        }
        return acc
      }, allOptionSetListsDefault)

      return {
        ...state,
        allOptionSetList,
      }

    case 'UPDATE_OPTION_SET_LISTS': {
      const { type, optionUpdatedLists } = action.payload
      const allOptionSetList = state.allOptionSetList || {}

      return {
        ...state,
        allOptionSetList: {
          ...allOptionSetList,
          [type]: optionUpdatedLists,
        },
      }
    }

    case 'SET_CATEGORY': {
      const { category } = action.payload
      return {
        ...state,
        category,
      }
    }

    case 'SET_ANCHOR_DRAGGING': {
      const { isAnchorDragging } = action.payload
      return {
        ...state,
        isAnchorDragging,
      }
    }

    case 'SET_METADATA_SAVE_THUMBNAIL_WITH_PREVIEW': {
      const { saveThumbnailWithPreview } = action.payload
      return {
        ...state,
        metadata: {
          ...state.metadata,
          saveThumbnailWithPreview,
        },
      }
    }

    default:
      return state
  }
}

function proxyTemplateEditorReducer(state: TemplateEditor, action: Action & Trace) {
  const updatedState = templateEditorReducer(state, action)

  const skipTrace = action.skipTrace

  if (!skipTrace) {
    const step: Step = {
      type: action.type,
      fromData: state,
      toData: updatedState,
      callback: (target: any, props: string | symbol, value: any) => stepCallback(target, props, value, getSaveBarId()),
    }

    addSteps(step)
  }

  return updatedState
}

export const TemplateEditorStore = createStore(proxyTemplateEditorReducer, DEFAULT_TEMPLATE_EDITOR_STORE)

function setLoading(extracting: boolean) {
  TemplateEditorStore.dispatch({ type: 'SET_LOADING', payload: { extracting }, skipTrace: true })
}

function addExtractedLayerStores(extractedLayerStores: TLayerStore[], skipTrace?: boolean) {
  TemplateEditorStore.dispatch({ type: 'ADD_EXTRACTED_LAYER_IDS', payload: { extractedLayerStores }, skipTrace })
}

/**
 * Delete extracted layer stores
 * Handles cascade delete for CHARM_NODE layers (C2 fix)
 * @param extractedLayerStores - Layer stores to delete
 * @param skipTrace - Whether to skip trace
 */
function deleteExtractedLayerStores(extractedLayerStores: TLayerStore[], skipTrace?: boolean) {
  const layersToDelete: TLayerStore[] = [...extractedLayerStores]
  const charmInstanceIdsToUnregister: string[] = []

  // Check for CHARM_NODE layers and cascade delete their CHARM children
  for (const store of extractedLayerStores) {
    const state = store.getState()

    if (state.type === ELayerType.CHARM_NODE) {
      const settings = state.settings as CharmNodeSettings | undefined
      const linkedProducts = settings?.linkedProducts || []

      // Collect all instanceIds from this CHARM_NODE
      for (const product of linkedProducts) {
        for (const transform of product.transforms || []) {
          charmInstanceIdsToUnregister.push(transform.instanceId)

          // Find the CHARM layer for this instance
          const charmLayer = getCharmLayerByInstanceId(transform.instanceId)
          if (charmLayer && !layersToDelete.includes(charmLayer)) {
            layersToDelete.push(charmLayer)
          }
        }
      }
    }

    // If deleting a CHARM layer, unregister it from the index
    if (state.type === ELayerType.CHARM) {
      const instanceId = (state.settings as any)?.productRef?.instanceId
      if (instanceId) {
        charmInstanceIdsToUnregister.push(instanceId)
      }
    }
  }

  // Mark all CHARM children as deleted (for undo/redo support)
  for (const store of layersToDelete) {
    const state = store.getState()
    if (state.type === ELayerType.CHARM) {
      store.dispatch({
        type: 'UPDATE_LAYER',
        payload: { state: { isDeletedOnEditor: true } },
        skipTrace: true,
      })
    }
  }

  // Unregister charm layers from index
  for (const instanceId of charmInstanceIdsToUnregister) {
    unregisterCharmLayer(instanceId)
  }

  TemplateEditorStore.dispatch({
    type: 'DELETE_EXTRACTED_LAYER_IDS',
    payload: { extractedLayerStores: layersToDelete },
    skipTrace,
  })
}

export function getExtractedLayerStores() {
  return TemplateEditorStore.getState().extractedLayerStores
}

/** This function return all layers include layers in multi-layout */
export function getExtractedCompositeLayerStores() {
  const extractedLayerStores = getExtractedLayerStores()

  const compositeLayerStores: TLayerStore[] = []

  extractedLayerStores.forEach(layerStore => {
    const layerState = layerStore.getState()

    if (layerState.isDeletedOnEditor) return

    compositeLayerStores.push(layerStore)

    const type = layerState.type
    if (type === 'multi-layout') {
      const optionSet = layerState.optionSet?.find(ot => ot.type === EOptionSet['MULTI_LAYOUT_OPTION'])

      if (!optionSet) return

      const layerStores = (optionSet.data?.['multi_layout']?.layouts || [])
        .map(layout => layout.layerIds.map(layerId => getLayerStoreById(layerId)))
        .flat()

      compositeLayerStores.push(...layerStores)
    }
  })

  return compositeLayerStores
}

function setExtractedLayerStores(extractedLayerStores: TLayerStore[], skipTrace?: boolean) {
  TemplateEditorStore.dispatch({ type: 'SET_EXTRACTED_LAYER_IDS', payload: { extractedLayerStores }, skipTrace })
}

function resetState(skipTrace?: boolean) {
  // Clear charm layer index to prevent stale entries when switching templates
  clearCharmLayerIndex()
  TemplateEditorStore.dispatch({ type: 'RESET_STATE', skipTrace })
}

function setOptionSetLists(optionSetLists: OptionSet[], skipTrace?: boolean) {
  TemplateEditorStore.dispatch({ type: 'SET_OPTION_SET_LISTS', payload: { optionSetLists }, skipTrace })
}

function resetClipartUsages(clipartsAdded: TemplateEditor[] = [], skipTrace?: boolean) {
  TemplateEditorStore.dispatch({
    type: 'SET_CLIPARTS',
    payload: { clipartsAdded },
    skipTrace,
  })
}

export const TemplateEditorStoreActions = {
  setLoading,
  getExtractedLayerStores,
  addExtractedLayerStores,
  deleteExtractedLayerStores,
  setExtractedLayerStores,
  resetState,
  setOptionSetLists,
  resetClipartUsages,
}

// Define a store for layer visibility
export const LayerVisibilityStore = createStore(LayerVisibilityStoreReducer, { layerVisibility: {} })

function LayerVisibilityStoreReducer(state: any, action: any) {
  const payload = action.payload

  switch (action.type) {
    case 'SET_LAYER_VISIBILITY':
      return {
        ...state,
        layerVisibility: {
          ...state.layerVisibility,
          [payload.layerId]: { ...(state.layerVisibility?.[payload.layerId] || {}), ...payload.visible },
        },
      }

    case 'RESET_LAYER_VISIBILITY':
      return {
        ...state,
        layerVisibility: null,
      }

    default:
      return state
  }
}
