export const CUSTOMERIO_EVENTS = {
  INSTALLED_APP: 'installed_app',
  REINSTALLED_APP: 'reinstalled_app',
  UNINSTALLED_APP: 'uninstalled_app',
  CREATED_FIRST_TEMPLATE: 'created_first_template',
  CREATED_FIRST_INTEGRATION: 'created_first_integration',
  PUBLISHED_FIRST_INTEGRATION: 'published_first_integration',
  REQUEST_FULFILLMENT_ORDER: 'request_fulfillment_order',
  ORDER_FULFILLED: 'order_fulfilled',
  ORDER_FAILED: 'order_failed',
  ORDER_SENT_TO_PRODUCTION: 'order_sent_to_production',
  ACHIEVED_FIRST_ORDER: 'achieved_first_order',
  FULFILLED_FIRST_ORDER: 'fulfilled_first_order',
  ACHIEVED_PROMOTION_REWARD: 'achieved_promotion_reward',
  MISSING_PROVIDER_CONNECTION: 'missing_provider_connection',
  EXPORT_ORDERS: 'export_orders',
  USED_AI_GEN_DESIGN: 'used_ai_gen_design',
  AI_CREDIT_REACHED_50: 'ai_credit_reached_50',
  AI_CREDIT_REACHED_80: 'ai_credit_reached_80',
  AI_CREDIT_REACHED_100: 'ai_credit_reached_100',
  PRODUCT_IMAGE_DIMENSION_MISMATCH: 'product_image_dimension_mismatch',
  ELVA_FEATURE_REQUEST_SUBMITTED: 'elva_feature_request_submitted',
}
