export type TailorKitAuthenticatedFetchBridgeStatus =
  | 'mapped-get'
  | 'mapped-form-action'
  | 'mapped-json-action'
  | 'pending-source-mapped-adapter'

export interface TailorKitAuthenticatedFetchBridgeDecision {
  id: string
  coreFlow: 'list' | 'create-existing-product' | 'detail' | 'save' | 'publish' | 'provider-import' | 'bulk' | 'support'
  adminRouteIds: readonly string[]
  upstreamSource: string
  upstreamEvidence: string
  upstreamEndpoint: string
  pageflyEndpoint: string | null
  status: TailorKitAuthenticatedFetchBridgeStatus
  notes: string
}

export type TailorKitPageFlyApiRouteBridgeStatus = 'source-mapped-adapter' | 'fail-closed-provisional-host-adapter'

export interface TailorKitPageFlyApiRouteBridgeDecision {
  method: 'GET' | 'POST' | 'PUT'
  path: string
  sourceDecisionIds: readonly string[]
  status: TailorKitPageFlyApiRouteBridgeStatus
  notes: string
}

/** Bridges copied TailorKit authenticatedFetch calls into PageFly app APIs without replacing UI behavior. */
export const tailorkitAuthenticatedFetchBridgeDecisions = [
  {
    id: 'preferences-read',
    coreFlow: 'list',
    adminRouteIds: ['personalized-products._index'],
    upstreamSource: 'app/routes/personalized-products._index/route.tsx',
    upstreamEvidence: "authenticatedFetch('/api/preferences')",
    upstreamEndpoint: 'GET /api/preferences',
    pageflyEndpoint: 'GET /theme-config',
    status: 'mapped-get',
    notes: 'Copied list clientLoader reads shop/theme setup state through the PageFly theme-config adapter.',
  },
  {
    id: 'personalized-products-list',
    coreFlow: 'list',
    adminRouteIds: ['personalized-products._index'],
    upstreamSource: 'app/routes/personalized-products._index/route.tsx',
    upstreamEvidence: 'dataSource="/api/personalized-products"',
    upstreamEndpoint: 'GET /api/personalized-products',
    pageflyEndpoint: 'GET /personalized-products',
    status: 'mapped-get',
    notes: 'Copied ListTable uses TailorKit withDataSource GET semantics; PageFly preserves query strings.',
  },
  {
    id: 'orders-list-read',
    coreFlow: 'list',
    adminRouteIds: ['orders._index', 'orders.$id'],
    upstreamSource: 'app/routes/orders._index/route.tsx',
    upstreamEvidence: 'dataSource="/api/orders"',
    upstreamEndpoint: 'GET /api/orders',
    pageflyEndpoint: 'GET /orders',
    status: 'mapped-get',
    notes: 'Copied Orders ListTable + detail loader read captured orders through the PageFly /orders adapter.',
  },
  {
    id: 'list-table-views-read',
    coreFlow: 'list',
    adminRouteIds: ['personalized-products._index', 'orders._index'],
    upstreamSource: 'app/components/ListTable.tsx',
    upstreamEvidence: 'authenticatedFetch(`/api/views?path=${location.pathname}`)',
    upstreamEndpoint: 'GET /api/views',
    pageflyEndpoint: 'GET /views',
    status: 'mapped-get',
    notes: 'Shared ListTable saved-views read; PageFly does not persist custom views and returns an empty list.',
  },
  {
    id: 'integration-detail-read',
    coreFlow: 'detail',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/routes/personalized-products.$id/route.tsx',
    upstreamEvidence: '`/api/integrations/${id}?mockup=${mockupId}&populateTemplate=1`',
    upstreamEndpoint: 'GET /api/integrations/:id',
    pageflyEndpoint: 'GET /personalized-products/:id',
    status: 'mapped-get',
    notes: 'Copied detail clientLoader loads editor data through the PageFly detail adapter.',
  },
  {
    id: 'variant-integrations-read',
    coreFlow: 'detail',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/ProductEditor/utilities/integrationData.ts',
    upstreamEvidence: "authenticatedFetch('/api/variants-integrations')",
    upstreamEndpoint: 'GET /api/variants-integrations',
    pageflyEndpoint: 'GET /variant-integrations',
    status: 'mapped-get',
    notes:
      'Copied ProductEditor initialization reads previously integrated variants from the app-scoped variant-integrations collection.',
  },
  {
    id: 'integration-product-variants-by-ids-read',
    coreFlow: 'detail',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/api/services/integrations.ts',
    upstreamEvidence: 'FETCH_PRODUCT_VARIANTS_BY_VARIANT_IDS',
    upstreamEndpoint: 'POST /api/integrations?action=fetchProductVariantsByVariantIds',
    pageflyEndpoint: 'POST /integration-product-variants',
    status: 'mapped-json-action',
    notes:
      'Copied ProductEditor variant initialization reads existing app-scoped variant integration snapshots instead of falling through to TailorKit Mongo models.',
  },
  {
    id: 'integration-all-product-variants-read',
    coreFlow: 'detail',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/routes/api.integrations/route.ts',
    upstreamEvidence: 'FETCH_ALL_PRODUCT_VARIANTS',
    upstreamEndpoint: 'POST /api/integrations?action=fetchAllProductVariants',
    pageflyEndpoint: 'POST /integration-all-product-variants',
    status: 'mapped-form-action',
    notes:
      'Copied ProductNVariantSelector (Charm builder + variant selector) lists all Shopify products/variants through ctx.ports.shopifyResources.products. Unlike the sibling fetchProductVariantsByVariantIds action, the upstream handler reads request.formData() instead of request.json(), so this is a form-action bridge.',
  },
  {
    id: 'integration-products-by-ids-read',
    coreFlow: 'detail',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/api/services/integrations.ts',
    upstreamEvidence: 'FETCH_PRODUCT_BY_PRODUCT_ID',
    upstreamEndpoint: 'POST /api/integrations?action=fetchProductByProductId',
    pageflyEndpoint: 'POST /integration-products',
    status: 'mapped-json-action',
    notes:
      'Copied ProductEditor variant fallback reads Shopify products through ctx.ports.shopifyResources.productsByIds.',
  },
  {
    id: 'overlay-lookup-read',
    coreFlow: 'detail',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/ProductEditor/components/ProductBaseSetting/MaskLayer/index.tsx',
    upstreamEvidence: '/api/overlay-lookup?product_title=',
    upstreamEndpoint: 'GET /api/overlay-lookup?product_title=:title',
    pageflyEndpoint: 'GET /overlay-lookup?product_title=:title',
    status: 'mapped-get',
    notes:
      'Premade mask overlay lookup is optional editor assistance; PageFly V0.1 returns an empty source-mapped catalog response instead of throwing a ProductEditor toast.',
  },
  {
    id: 'overlay-lookup-transparent-regions-write',
    coreFlow: 'detail',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource:
      'app/modules/ProductEditor/components/IntegrationInspector/Integrate/MockupLayersManager/index.tsx',
    upstreamEvidence: "authenticatedFetch('/api/overlay-lookup', {",
    upstreamEndpoint: 'POST /api/overlay-lookup',
    pageflyEndpoint: 'POST /overlay-lookup',
    status: 'mapped-json-action',
    notes:
      'Copied ProductEditor caches detected transparent mask regions through the overlay route; PageFly stores that metadata in scoped appData instead of importing TailorKit Asset models.',
  },
  {
    id: 'template-usage-check',
    coreFlow: 'detail',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/ProductEditor/components/Canvas/components/PrintAreasBar/ModalEditTemplate.tsx',
    upstreamEvidence: 'TEMPLATES_ACTIONS.CHECK_TEMPLATE_USAGE',
    upstreamEndpoint: 'POST /api/templates?action=checkTemplateUsage',
    pageflyEndpoint: 'POST /template-usage',
    status: 'mapped-json-action',
    notes:
      'Copied ModalEditTemplate uses raw fetch to check whether a template is reused; PageFly maps the exact action to app-scoped template snapshots.',
  },
  {
    id: 'template-list-read',
    coreFlow: 'detail',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/api/services/templates.ts',
    upstreamEvidence: 'async list(',
    upstreamEndpoint: 'GET /api/templates',
    pageflyEndpoint: 'GET /templates',
    status: 'mapped-get',
    notes:
      'Copied ProductEditor template picker lists merchant template snapshots through app-scoped TailorKit template data.',
  },
  {
    id: 'template-detail-read',
    coreFlow: 'detail',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/api/services/templates.ts',
    upstreamEvidence: 'async getById(id: string)',
    upstreamEndpoint: 'GET /api/templates/:id',
    pageflyEndpoint: 'GET /templates/:id',
    status: 'mapped-get',
    notes:
      'Copied ProductEditor template picker reads selected template detail through app-scoped TailorKit template data.',
  },
  {
    id: 'template-save-action',
    coreFlow: 'save',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/TemplateEditor/hooks/useSaveTemplate.tsx',
    upstreamEvidence: 'TemplatesService.create(templateEditor._id, formData)',
    upstreamEndpoint: 'POST /api/templates/:id type=saveTemplate',
    pageflyEndpoint: 'POST /templates/:id/save',
    status: 'mapped-json-action',
    notes:
      'Copied TemplateEditor save sends compressed FormData through TemplatesService.create; PageFly decompresses it at the admin boundary and upserts the app-scoped template snapshot without importing TailorKit Template models.',
  },
  {
    id: 'option-sets-list-read',
    coreFlow: 'detail',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/TemplateEditor/hooks/useInitTemplate.tsx',
    upstreamEvidence: 'authenticatedFetch(`/api/option-sets`)',
    upstreamEndpoint: 'GET /api/option-sets',
    pageflyEndpoint: 'GET /option-sets',
    status: 'mapped-get',
    notes:
      'Copied ProductEditor initializes TemplateEditor option-set lists during canvas setup; PageFly reads the app-scoped option-sets collection with TailorKit fetchList shape.',
  },
  {
    id: 'prompt-presets-list-read',
    coreFlow: 'detail',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/TemplateEditor/components/Editor/hooks/useElementActions.ts',
    upstreamEvidence: "authenticatedFetch('/api/prompt-presets')",
    upstreamEndpoint: 'GET /api/prompt-presets',
    pageflyEndpoint: 'GET /prompt-presets',
    status: 'mapped-get',
    notes:
      'Copied TemplateEditor mounts useElementActions broadly and reads AI prompt presets during editor setup; PageFly V0.1 returns an empty prompt catalog instead of crashing the admin editor.',
  },
  {
    id: 'shopify-media-files-query',
    coreFlow: 'support',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/modals/ImageSelector/utilities/fetchMediaList.ts',
    upstreamEvidence: 'FETCH_MEDIA_LISTS',
    upstreamEndpoint: 'POST /api/files?action=fetchMediaLists',
    pageflyEndpoint: 'POST /files/query-media',
    status: 'mapped-json-action',
    notes:
      'Copied ImageSelector media library browses merchant Shopify media images through ctx.ports.shopifyResources.mediaFiles with cursor pagination.',
  },
  {
    id: 'custom-font-files-query',
    coreFlow: 'support',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/TemplateEditor/elements/hooks/useQueryFonts.ts',
    upstreamEvidence: 'QUERY_FONT_FILES',
    upstreamEndpoint: 'POST /api/files?action=queryFontFiles',
    pageflyEndpoint: 'POST /files/query-fonts',
    status: 'mapped-json-action',
    notes:
      'Copied typography panels query merchant-uploaded custom fonts from Shopify files; PageFly V0.1 returns an empty custom-font page while Google fonts keep working.',
  },
  {
    id: 'custom-mask-files-query',
    coreFlow: 'support',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/TemplateEditor/elements/hooks/useQueryMasks.ts',
    upstreamEvidence: 'QUERY_MASK_FILES',
    upstreamEndpoint: 'POST /api/files?action=queryMaskFiles',
    pageflyEndpoint: 'POST /files/query-masks',
    status: 'mapped-json-action',
    notes:
      'Copied mask panels query merchant-uploaded custom masks from Shopify files; PageFly V0.1 returns an empty custom-mask page while built-in mask options stay available.',
  },
  {
    id: 'tutorials-list-read',
    coreFlow: 'support',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/TemplateEditor/components/Outline/ToolSidebar/panels/TutorialsToolPanel.tsx',
    upstreamEvidence: "authenticatedFetch('/api/tutorials')",
    upstreamEndpoint: 'GET /api/tutorials',
    pageflyEndpoint: 'GET /tutorials',
    status: 'mapped-get',
    notes:
      'Copied editor tutorial panel is optional admin help content; PageFly V0.1 returns an empty list rather than importing TailorKit tutorial CMS.',
  },
  {
    id: 'user-journey-read',
    coreFlow: 'support',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/TourGuides/TriggerTourProvider/index.tsx',
    upstreamEvidence: '/api/user-journey?types=',
    upstreamEndpoint: 'GET /api/user-journey?type=:type|types=:types',
    pageflyEndpoint: 'GET /user-journey',
    status: 'mapped-get',
    notes:
      'Copied editor trigger tours batch-read completion state; PageFly stores that state in scoped app data so dismissed editor tours stay dismissed across sessions.',
  },
  {
    id: 'user-journey-save-progress',
    coreFlow: 'support',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/TourGuides/TemplateEditorQuickTour/fns.ts',
    upstreamEvidence: 'USER_JOURNEY_ACTIONS.SAVE_ONBOARDING_PROGRESS_STATE',
    upstreamEndpoint: 'POST /api/user-journey?action=save_onboarding_progress_state',
    pageflyEndpoint: 'POST /user-journey',
    status: 'mapped-json-action',
    notes:
      'Copied editor tours mark skip/finish through TailorKit user-journey progress; PageFly maps it to app-scoped user journey records instead of TailorKit Mongo.',
  },
  {
    id: 'template-upload-files',
    coreFlow: 'support',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/ProductEditor/withTemplateLayerUploader.tsx',
    upstreamEvidence: 'actionUrl={`/api/templates?action=${TEMPLATES_ACTIONS.UPLOAD_FILES}`}',
    upstreamEndpoint: 'POST /api/templates?action=uploadFiles',
    pageflyEndpoint: 'POST /files/upload',
    status: 'mapped-form-action',
    notes:
      'ProductEditor/ImageSelector uploads are base64-bridged at the island (multipart FormData → JSON) and run the real Shopify staged-upload (or S3 fallback) flow server-side through ctx.ports.shopifyResources.uploadFiles.',
  },
  {
    id: 'template-get-cliparts-details',
    coreFlow: 'support',
    adminRouteIds: ['personalized-products.loading'],
    upstreamSource: 'app/api/services/templates.ts',
    upstreamEvidence: 'TEMPLATES_ACTIONS.GET_CLIPARTS_DETAILS',
    upstreamEndpoint: 'POST /api/templates?action=getClipartsDetails',
    pageflyEndpoint: null,
    status: 'pending-source-mapped-adapter',
    notes:
      'Loading route clipart flow reads TailorKit public clipart/template catalog data. PageFly V0.1 existing-product admin flow keeps this fail-closed until a template catalog port exists.',
  },
  {
    id: 'template-get-by-ids',
    coreFlow: 'detail',
    adminRouteIds: ['personalized-products.$id', 'personalized-products.loading'],
    upstreamSource: 'app/api/services/templates.ts',
    upstreamEvidence: 'TEMPLATES_ACTIONS.GET_TEMPLATES_BY_IDS',
    upstreamEndpoint: 'POST /api/templates?action=getTemplatesByIds',
    pageflyEndpoint: 'POST /templates-by-ids',
    status: 'mapped-json-action',
    notes:
      'Copied ProductEditor preview and loading route can read existing merchant template snapshots by id through app-scoped TailorKit template data.',
  },
  {
    id: 'template-clone-clipart-to-template',
    coreFlow: 'support',
    adminRouteIds: ['personalized-products.loading'],
    upstreamSource: 'app/utils/integration/templateDuplication.ts',
    upstreamEvidence: 'cloneClipartToTemplate',
    upstreamEndpoint: 'POST /api/templates?action=cloneClipartToTemplate',
    pageflyEndpoint: null,
    status: 'pending-source-mapped-adapter',
    notes:
      'Loading route can clone public clipart into a merchant template. PageFly V0.1 blocks this path instead of cloning against unavailable TailorKit template storage.',
  },
  {
    id: 'integration-save-action',
    coreFlow: 'save',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/ProductEditor/hooks/useSaveIntegration.ts',
    upstreamEvidence: "authenticatedFetch('/api/integration'",
    upstreamEndpoint: 'POST /api/integration action=save-product',
    pageflyEndpoint: 'PUT /personalized-products/:id',
    status: 'mapped-form-action',
    notes: 'Compressed TailorKit save payload is decompressed at the PageFly boundary and sent to appData.',
  },
  {
    id: 'integration-publish-action',
    coreFlow: 'publish',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/ProductEditor/hooks/useUnifiedPublish.ts',
    upstreamEvidence: "authenticatedFetch('/api/integration'",
    upstreamEndpoint: 'POST /api/integration action=publish-product',
    pageflyEndpoint: 'POST /personalized-products/:id/publish',
    status: 'mapped-form-action',
    notes: 'Publish action stays a form-action bridge; ProductEditor behavior remains copied from TailorKit.',
  },
  {
    id: 'integration-unpublish-action',
    coreFlow: 'publish',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/ProductEditor/hooks/useUnifiedPublish.ts',
    upstreamEvidence: "authenticatedFetch('/api/integration'",
    upstreamEndpoint: 'POST /api/integration action=unpublish-product',
    pageflyEndpoint: 'POST /personalized-products/:id/unpublish',
    status: 'mapped-form-action',
    notes: 'Unpublish action is part of the same copied ProductEditor publish flow.',
  },
  {
    id: 'integration-shared-templates-read',
    coreFlow: 'publish',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/api/services/integrations.ts',
    upstreamEvidence: 'CHECK_SHARED_TEMPLATES_WITH_PUBLISHED',
    upstreamEndpoint: 'POST /api/integrations?action=checkSharedTemplatesWithPublished',
    pageflyEndpoint: 'POST /shared-template-integrations',
    status: 'mapped-json-action',
    notes: 'Copied publish UI checks shared templates against app-scoped published integration snapshots.',
  },
  {
    id: 'published-integrations-by-variant-ids-read',
    coreFlow: 'publish',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/TemplateEditor/modals/RepublishProductsModal.tsx',
    upstreamEvidence: 'FETCH_INTEGRATIONS_BY_VARIANT_IDS',
    upstreamEndpoint: 'POST /api/integrations?action=fetchIntegrationsByVariantIds',
    pageflyEndpoint: 'POST /published-integrations-by-variant-ids',
    status: 'mapped-json-action',
    notes:
      'Copied TemplateEditor republish modal finds already-published personalized products from active variant integrations; PageFly reads scoped integration and variant snapshots.',
  },
  {
    id: 'published-integrations-by-template-read',
    coreFlow: 'save',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/TemplateEditor/components/Header/SaveTemplateButton.tsx',
    upstreamEvidence: 'FETCH_INTEGRATIONS_BY_TEMPLATE',
    upstreamEndpoint: 'POST /api/integrations?action=fetchIntegrationsByTemplate',
    pageflyEndpoint: 'POST /published-integrations-by-template',
    status: 'mapped-json-action',
    notes:
      'Copied TemplateEditor save flow checks whether a saved template is used by published personalized products before showing republish actions.',
  },
  {
    id: 'products-by-template-read',
    coreFlow: 'support',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/TemplateEditor/components/Header/SaveTemplateButton.tsx',
    upstreamEvidence: '`/api/products/?templateId=${templateId}`',
    upstreamEndpoint: 'GET /api/products?templateId=:templateId',
    pageflyEndpoint: 'GET /products-by-template?templateId=:templateId',
    status: 'mapped-get',
    notes:
      'Copied TemplateEditor integrated-products modal lists Shopify products whose personalized product snapshots use the current template.',
  },
  {
    id: 'option-set-layer-usage-read',
    coreFlow: 'support',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/TemplateEditor/elements/fns.ts',
    upstreamEvidence: 'FIND_LAYER_BEING_USED',
    upstreamEndpoint: 'POST /api/option-sets?action=findLayerBeingUsed',
    pageflyEndpoint: 'POST /option-set-layer-usage',
    status: 'mapped-json-action',
    notes:
      'Copied TemplateEditor duplicate/unsync option-set flow counts layers referencing the option set through scoped TailorKit layer snapshots.',
  },
  {
    id: 'preferences-mutation',
    coreFlow: 'support',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/ProductEditor/components/UnifiedHeader/index.tsx',
    upstreamEvidence: "authenticatedFetch('/api/preferences', {",
    upstreamEndpoint: 'POST /api/preferences',
    pageflyEndpoint: 'POST /preferences',
    status: 'mapped-form-action',
    notes:
      'UPDATE_OCCURRED_EVENT and GlobalStyling (GET/UPDATE_GLOBAL_STYLING) preference reads/writes are stored in TailorKit app-scoped personalizer settings.',
  },
  {
    id: 'integrations-bulk-publish-actions',
    coreFlow: 'bulk',
    adminRouteIds: ['personalized-products._index'],
    upstreamSource: 'app/routes/personalized-products._index/route.tsx',
    upstreamEvidence: '`/api/integrations?action=${action}`',
    upstreamEndpoint: 'POST /api/integrations?action=publishPersonalizedProducts|unpublishPersonalizedProducts',
    pageflyEndpoint: 'POST /integrations-bulk',
    status: 'mapped-form-action',
    notes:
      'List bulk publish/unpublish keeps TailorKit row selection behavior and routes each integration id through appData.',
  },
  {
    id: 'integrations-bulk-delete-action',
    coreFlow: 'bulk',
    adminRouteIds: ['personalized-products._index'],
    upstreamSource: 'app/routes/personalized-products._index/route.tsx',
    upstreamEvidence: 'DELETE_PERSONALIZED_PRODUCTS',
    upstreamEndpoint: 'POST /api/integrations?action=deletePersonalizedProducts',
    pageflyEndpoint: 'POST /integrations-bulk',
    status: 'mapped-form-action',
    notes:
      'Copied list bulk delete is mapped to app-scoped integration tombstones and variant/template snapshot tombstones.',
  },
  {
    id: 'variant-metafields-read',
    coreFlow: 'provider-import',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/ProductEditor/utilities/getVariantMetafields.ts',
    upstreamEvidence: 'FETCH_PRODUCT_VARIANT_METAFIELDS',
    upstreamEndpoint: 'POST /api/integrations?action=fetchProductVariantMetafields',
    pageflyEndpoint: null,
    status: 'pending-source-mapped-adapter',
    notes:
      'Imported/POD product setup reads Shopify variant metafields; PageFly does not expose a variant-metafields port yet, so this path stays fail-closed instead of using fake dimensions.',
  },
  {
    id: 'provider-connection-detail-read',
    coreFlow: 'provider-import',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/routes/settings_.providers.connection.$id/route.tsx',
    upstreamEvidence: 'authenticatedFetch(`/api/providers-connection/${params.id}`)',
    upstreamEndpoint: 'GET /api/providers-connection/:id',
    pageflyEndpoint: null,
    status: 'pending-source-mapped-adapter',
    notes:
      'Imported/POD product publish readiness checks provider connection details. PageFly V0.1 keeps provider connection reads fail-closed because provider import is deferred.',
  },
  {
    id: 'ai-mockup-scenes-read',
    coreFlow: 'support',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/ProductEditor/components/ProductBaseSetting/AIMockup/modals/AIMockupModal.tsx',
    upstreamEvidence: "authenticatedFetch('/api/ai-mockup-scenes', { preferCache: true })",
    upstreamEndpoint: 'GET /api/ai-mockup-scenes',
    pageflyEndpoint: null,
    status: 'pending-source-mapped-adapter',
    notes:
      'AI mockup scene catalog is a ProductEditor support surface. PageFly V0.1 keeps it fail-closed until AI mockup entitlement, credits, and media ports are modeled.',
  },
  {
    id: 'ai-mockup-generate-action',
    coreFlow: 'support',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/ProductEditor/components/ProductBaseSetting/AIMockup/modals/AIMockupModal.tsx',
    upstreamEvidence: "authenticatedFetch('/api/ai-mockup-scenes', {",
    upstreamEndpoint: 'POST /api/ai-mockup-scenes',
    pageflyEndpoint: null,
    status: 'pending-source-mapped-adapter',
    notes:
      'AI mockup generation depends on TailorKit AI credits/media services. PageFly V0.1 must not return fake generated media.',
  },
  {
    id: 'ai-mockup-upload-action',
    coreFlow: 'support',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource:
      'app/modules/ProductEditor/components/ProductBaseSetting/AIMockup/modals/ApplyAIMockupsConfirmationModal.tsx',
    upstreamEvidence: "authenticatedFetch('/api/mockup-upload', {",
    upstreamEndpoint: 'POST /api/mockup-upload',
    pageflyEndpoint: null,
    status: 'pending-source-mapped-adapter',
    notes:
      'AI mockup base64 upload depends on Shopify Files/media upload plumbing that is not exposed as an app-platform port yet.',
  },
  {
    id: 'ai-mockup-shopify-product-media-write',
    coreFlow: 'support',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource:
      'app/modules/ProductEditor/components/ProductBaseSetting/AIMockup/modals/ApplyAIMockupsConfirmationModal.tsx',
    upstreamEvidence: 'authenticatedFetch(`/api/shopify/products/${productId}`, {',
    upstreamEndpoint: 'POST /api/shopify/products/:productId',
    pageflyEndpoint: null,
    status: 'pending-source-mapped-adapter',
    notes:
      'Applying AI mockups mutates Shopify product media. PageFly keeps this support path blocked until media ownership is explicitly ported.',
  },
  {
    id: 'background-removal-service-action',
    coreFlow: 'support',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/TemplateEditor/utils/removeImageBackground.ts',
    upstreamEvidence: "fetch('/api/services', {",
    upstreamEndpoint: 'POST /api/services action=remove-background',
    pageflyEndpoint: null,
    status: 'pending-source-mapped-adapter',
    notes:
      'TemplateEditor background-removal API fallback depends on TailorKit service/media plumbing. PageFly V0.1 keeps it fail-closed and still allows external image fetches.',
  },
  {
    id: 'colour-guide-upload-action',
    coreFlow: 'support',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/TemplateEditor/elements/components/Text/ColorOptionSet/ColourGuideUpload.tsx',
    upstreamEvidence: "authenticatedFetch('/api/colour-guide/upload', {",
    upstreamEndpoint: 'POST /api/colour-guide/upload',
    pageflyEndpoint: 'POST /files/colour-guide-upload',
    status: 'mapped-form-action',
    notes:
      'Colour-guide single-file upload is base64-bridged at the island and written to S3 through ctx.ports.shopifyResources.uploadColourGuide, mirroring the upstream S3-only colour-guide route.',
  },
  {
    id: 'emoji-picker-apply-action',
    coreFlow: 'save',
    adminRouteIds: ['storefront-setup'],
    upstreamSource: 'app/routes/storefront-setup.storefront/components/EmojiPickerCard.tsx',
    upstreamEvidence: "authenticatedFetch('/api/emoji-picker/apply-to-all', {",
    upstreamEndpoint: 'POST /api/emoji-picker/apply-to-all',
    pageflyEndpoint: 'POST /emoji-picker/apply-to-all',
    status: 'mapped-json-action',
    notes:
      'Sales Tools Storefront-tab "apply emojis to all". PageFly acknowledges with a contract-shaped success; the deep layer-wide mutation is deferred (needs a host Layer-store port PageFly does not yet expose).',
  },
  {
    id: 'option-pricing-ensure-action',
    coreFlow: 'save',
    adminRouteIds: ['storefront-setup'],
    // The Upsell tab (storefront-setup.sales) was dropped (OneTick); the surviving caller is the Storefront
    // tab's ProductPreviewInCartCard → InstallAppEmbedActivator, which fires ENSURE_PRICING_PRODUCT on mount.
    upstreamSource: 'app/components/InstallAppEmbedActivator.tsx',
    upstreamEvidence: "authenticatedFetch('/api/option-pricing', {",
    upstreamEndpoint: 'POST /api/option-pricing',
    pageflyEndpoint: 'POST /option-pricing',
    status: 'mapped-json-action',
    notes:
      'Sales Tools Storefront-tab ENSURE_PRICING_PRODUCT (InstallAppEmbedActivator session-once mount). PageFly acknowledges with a contract-shaped success; real hidden-product creation is deferred (needs a host ShopifyResourcePort.createHiddenProduct capability PageFly does not yet expose).',
  },
  {
    id: 'live-charm-products-read',
    coreFlow: 'support',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/TemplateEditor/components/Outline/ToolSidebar/panels/hooks/useLiveCharmProducts.ts',
    upstreamEvidence: 'fetch(`/api/charm-products?ids=${encodeURIComponent(idsToFetch.join',
    upstreamEndpoint: 'GET /api/charm-products?ids=:ids',
    pageflyEndpoint: 'GET /charm-products',
    status: 'mapped-get',
    notes:
      'Copied charm picker reads live product title/price/availability by id through ctx.ports.shopifyResources.charmProducts.',
  },
  {
    id: 'font-combination-suggestions-read',
    coreFlow: 'support',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/stores/modules/font-combination-suggestions.ts',
    upstreamEvidence: "authenticatedFetch('/api/ai-assistant/suggest-font-combinations'",
    upstreamEndpoint: 'POST /api/ai-assistant/suggest-font-combinations',
    pageflyEndpoint: 'POST /font-combination-suggestions',
    status: 'mapped-json-action',
    notes:
      'Copied ProductEditor prefetches AI font-combination suggestions on mount. PageFly V0.1 returns an empty suggestion set instead of throwing because the AI catalog/credit flow is not ported.',
  },
  {
    id: 'shopify-products-by-ids-read',
    coreFlow: 'support',
    adminRouteIds: ['personalized-products._index', 'personalized-products.loading', 'personalized-products.$id'],
    upstreamSource: 'app/routes/api.shopify/route.ts',
    upstreamEvidence: 'SHOPIFY_API_ACTIONS.GET_PRODUCTS',
    upstreamEndpoint: 'GET /api/shopify?action=getProducts&ids=:ids',
    pageflyEndpoint: 'GET /shopify-products?ids=:ids',
    status: 'mapped-get',
    notes:
      'Copied RowActions/loading/ProductSelector preview reads products by id through ctx.ports.shopifyResources; ProductEditor provider-import save also reuses this endpoint after import.',
  },
  {
    id: 'shopify-product-images-read',
    coreFlow: 'support',
    adminRouteIds: ['personalized-products.loading'],
    upstreamSource: 'app/routes/api.shopify/route.ts',
    upstreamEvidence: "case 'getProductImages'",
    upstreamEndpoint: 'GET /api/shopify?action=getProductImages&productId=:id',
    pageflyEndpoint: 'GET /shopify-product-images?productId=:id',
    status: 'mapped-get',
    notes:
      'Copied simplified-onboarding product-image lookup is derived from ctx.ports.shopifyResources.productsByIds snapshots.',
  },
  {
    id: 'product-options-read',
    coreFlow: 'support',
    adminRouteIds: ['personalized-products.loading'],
    upstreamSource: 'app/routes/api.products/route.ts',
    upstreamEvidence: "const source = url.searchParams.get('source') || 'existing'",
    upstreamEndpoint: 'GET /api/products',
    pageflyEndpoint: 'GET /product-options',
    status: 'mapped-get',
    notes:
      'PageFly exposes normalized products and variants through ctx.ports.shopifyResources for scaffold/admin selectors.',
  },
  {
    id: 'dummy-products-suggestions-read',
    coreFlow: 'support',
    adminRouteIds: ['personalized-products.loading'],
    upstreamSource: 'app/modules/ProductSelector/hooks/useDummyProductsData.ts',
    upstreamEvidence: '/api/products?source=dummy&onlySuggestions=true',
    upstreamEndpoint: 'GET /api/products?source=dummy&onlySuggestions=true',
    pageflyEndpoint: 'GET /dummy-products-suggestions',
    status: 'mapped-get',
    notes:
      'Copied loading route mounts useDummyProductsData unconditionally. PageFly V0.1 maps this read-only TailorKit dummy suggestion request to an empty list so existing-product loading is not blocked by provider/import support.',
  },
  {
    id: 'product-selector-existing-products-read',
    coreFlow: 'create-existing-product',
    adminRouteIds: ['personalized-products._index', 'personalized-products.loading'],
    upstreamSource: 'app/modules/ProductSelector/ProductList/index.tsx',
    upstreamEvidence: '`/api/products?source=${source}${catParam}${searchParam}${afterParam}${statusParam}`',
    upstreamEndpoint: 'GET /api/products?source=existing',
    pageflyEndpoint: 'GET /products?source=existing',
    status: 'mapped-get',
    notes:
      'Copied TailorKit ProductSelector existing-product reads are mapped through ctx.ports.shopifyResources.products.',
  },
  {
    id: 'product-selector-existing-categories-read',
    coreFlow: 'create-existing-product',
    adminRouteIds: ['personalized-products._index', 'personalized-products.loading'],
    upstreamSource: 'app/modules/ProductSelector/ProductList/index.tsx',
    upstreamEvidence: '`/api/products/categories?source=${source}&search=${searchValue}${productId ?',
    upstreamEndpoint: 'GET /api/products/categories?source=existing',
    pageflyEndpoint: 'GET /product-categories?source=existing',
    status: 'mapped-get',
    notes:
      'Copied TailorKit ProductSelector category reads are mapped through ctx.ports.shopifyResources.productCategories.',
  },
  {
    id: 'product-selector-providers-read',
    coreFlow: 'create-existing-product',
    adminRouteIds: ['personalized-products._index', 'personalized-products.loading'],
    upstreamSource: 'app/modules/ProductSelector/index.tsx',
    upstreamEvidence: 'authenticatedFetch(`/api/providers`, { preferCache: true })',
    upstreamEndpoint: 'GET /api/providers',
    pageflyEndpoint: 'GET /providers',
    status: 'mapped-get',
    notes:
      'V0.1 supports existing Shopify products only; provider list returns empty so copied ProductSelector does not expose provider import flows.',
  },
  {
    id: 'product-selector-duplicate-existing-product',
    coreFlow: 'create-existing-product',
    adminRouteIds: ['personalized-products._index', 'personalized-products.loading'],
    upstreamSource: 'app/modules/ProductSelector/index.tsx',
    upstreamEvidence: 'PRODUCT_MUTATION_ACTIONS.DUPLICATE_EXISTING_PRODUCT',
    upstreamEndpoint: 'POST /api/products action=duplicate_existing_product',
    pageflyEndpoint: 'POST /products',
    status: 'mapped-form-action',
    notes:
      'Copied TailorKit ProductSelector duplicate-existing-product mutation is routed through ctx.ports.shopifyResources.duplicateProduct.',
  },
  {
    id: 'product-selector-provider-product-detail-read',
    coreFlow: 'provider-import',
    adminRouteIds: ['personalized-products._index'],
    upstreamSource: 'app/modules/ProductSelector/ProductEditor/index.tsx',
    upstreamEvidence: 'authenticatedFetch(`/api/products/${productId}?source=${source}`, { preferCache: true })',
    upstreamEndpoint: 'GET /api/products/:id?source=:source',
    pageflyEndpoint: null,
    status: 'pending-source-mapped-adapter',
    notes:
      'Provider ProductSelector editor reads provider product detail; PageFly V0.1 existing-product flow must not fake Printify/provider catalog detail without a dedicated provider catalog port.',
  },
  {
    id: 'product-selector-provider-product-providers-read',
    coreFlow: 'provider-import',
    adminRouteIds: ['personalized-products._index'],
    upstreamSource: 'app/modules/ProductSelector/ProductEditor/index.tsx',
    upstreamEvidence:
      'authenticatedFetch(`/api/products/providers/${productId}?source=${source}`, { preferCache: true })',
    upstreamEndpoint: 'GET /api/products/providers/:id?source=:source',
    pageflyEndpoint: null,
    status: 'pending-source-mapped-adapter',
    notes:
      'Provider ProductSelector editor reads provider options; PageFly keeps this fail-closed until a source-mapped provider option adapter exists.',
  },
  {
    id: 'product-selector-provider-product-variants-read',
    coreFlow: 'provider-import',
    adminRouteIds: ['personalized-products._index'],
    upstreamSource: 'app/modules/ProductSelector/ProductEditor/index.tsx',
    upstreamEvidence:
      'authenticatedFetch(`/api/products/variants/${productId}?source=${source}&providerId=${value}`, {',
    upstreamEndpoint: 'GET /api/products/variants/:id?source=:source&providerId=:providerId',
    pageflyEndpoint: null,
    status: 'pending-source-mapped-adapter',
    notes:
      'Provider ProductSelector editor reads provider variant/cost data; PageFly keeps this fail-closed until provider variant pricing is modeled through app-platform ports.',
  },
  {
    id: 'product-selector-products',
    coreFlow: 'provider-import',
    adminRouteIds: ['personalized-products._index', 'personalized-products.loading'],
    upstreamSource: 'app/modules/ProductSelector/index.tsx',
    upstreamEvidence: 'PROVIDER_INTEGRATION_ACTION.IMPORT_PRODUCTS_TO_SHOPIFY',
    upstreamEndpoint: 'POST /api/products for unsupported actions and non-existing ProductSelector sources',
    pageflyEndpoint: null,
    status: 'pending-source-mapped-adapter',
    notes:
      'ProductSelector import/provider/non-existing source mutations remain pending; do not fake provider product data.',
  },
  {
    id: 'provider-dummy-product-import',
    coreFlow: 'provider-import',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/ProductEditor/hooks/useSaveIntegration.ts',
    upstreamEvidence: 'PROVIDER_INTEGRATION_ACTION.IMPORT_DUMMY_PRODUCTS_TO_SHOPIFY',
    upstreamEndpoint: 'POST /api/providers-integration/dummy action=import-dummy-products-to-shopify',
    pageflyEndpoint: null,
    status: 'pending-source-mapped-adapter',
    notes:
      'Temporary/dummy ProductEditor save imports a non-existing product into Shopify before normal save; V0.1 existing-product save must not run this branch without a source-mapped provider import port.',
  },
  {
    id: 'provider-imported-product-rollback-delete',
    coreFlow: 'provider-import',
    adminRouteIds: ['personalized-products.$id'],
    upstreamSource: 'app/modules/ProductEditor/hooks/useSaveIntegration.ts',
    upstreamEvidence: 'SHOPIFY_API_ACTIONS.DELETE_PRODUCT',
    upstreamEndpoint: 'GET /api/shopify?action=deleteProduct&id=:id',
    pageflyEndpoint: null,
    status: 'pending-source-mapped-adapter',
    notes:
      'Temporary/dummy ProductEditor save rolls back the Shopify product when import/save fails; this stays blocked until the provider import port owns product lifecycle cleanup.',
  },
] as const satisfies readonly TailorKitAuthenticatedFetchBridgeDecision[]

/** Active PageFly app API routes and the TailorKit source decisions that justify them. */
export const tailorkitPageFlyApiRouteBridgeDecisions = [
  {
    method: 'GET',
    path: '/product-options',
    sourceDecisionIds: ['product-options-read'],
    status: 'source-mapped-adapter',
    notes: 'Backs PageFly normalized product/variant setup options through the Shopify resource port.',
  },
  {
    method: 'GET',
    path: '/shopify-products',
    sourceDecisionIds: ['shopify-products-by-ids-read'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied TailorKit GET_PRODUCTS lookups without exposing raw Shopify clients.',
  },
  {
    method: 'GET',
    path: '/shopify-product-images',
    sourceDecisionIds: ['shopify-product-images-read'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied getProductImages lookups from normalized Shopify product snapshots.',
  },
  {
    method: 'GET',
    path: '/products',
    sourceDecisionIds: ['product-selector-existing-products-read'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied TailorKit ProductSelector existing-product reads through the Shopify resource port.',
  },
  {
    method: 'GET',
    path: '/dummy-products-suggestions',
    sourceDecisionIds: ['dummy-products-suggestions-read'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied loading route dummy suggestion reads with an empty V0.1 catalog.',
  },
  {
    method: 'GET',
    path: '/product-categories',
    sourceDecisionIds: ['product-selector-existing-categories-read'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied TailorKit ProductSelector existing category reads through the Shopify resource port.',
  },
  {
    method: 'GET',
    path: '/providers',
    sourceDecisionIds: ['product-selector-providers-read'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied TailorKit ProductSelector provider discovery with an empty V0.1 provider list.',
  },
  {
    method: 'GET',
    path: '/personalized-products',
    sourceDecisionIds: ['personalized-products-list'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied ListTable GET dataSource semantics.',
  },
  {
    method: 'POST',
    path: '/preferences',
    sourceDecisionIds: ['preferences-mutation'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied ProductEditor UPDATE_OCCURRED_EVENT and GlobalStyling preference reads/writes.',
  },
  {
    method: 'POST',
    path: '/integrations-bulk',
    sourceDecisionIds: ['integrations-bulk-publish-actions', 'integrations-bulk-delete-action'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied list bulk publish/unpublish/delete actions.',
  },
  {
    method: 'POST',
    path: '/products',
    sourceDecisionIds: ['product-selector-duplicate-existing-product'],
    status: 'source-mapped-adapter',
    notes:
      'Backs copied TailorKit ProductSelector duplicate-existing-product mutation through the Shopify resource port.',
  },
  {
    method: 'POST',
    path: '/personalized-products',
    sourceDecisionIds: ['product-selector-products'],
    status: 'fail-closed-provisional-host-adapter',
    notes: 'Create flow returns 501 until copied TailorKit loading/ProductSelector routes own the action.',
  },
  {
    method: 'GET',
    path: '/personalized-products/:id',
    sourceDecisionIds: ['integration-detail-read'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied detail route clientLoader integration read.',
  },
  {
    method: 'GET',
    path: '/variant-integrations',
    sourceDecisionIds: ['variant-integrations-read'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied ProductEditor initialization all-variant-integrations read from scoped appData.',
  },
  {
    method: 'POST',
    path: '/integration-product-variants',
    sourceDecisionIds: ['integration-product-variants-by-ids-read'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied ProductEditor variant initialization by reading scoped variant integration snapshots.',
  },
  {
    method: 'POST',
    path: '/integration-all-product-variants',
    sourceDecisionIds: ['integration-all-product-variants-read'],
    status: 'source-mapped-adapter',
    notes:
      'Backs copied ProductNVariantSelector (Charm builder + variant selector) product/variant listing through the Shopify resource port, compressed the same way the upstream FETCH_ALL_PRODUCT_VARIANTS action does.',
  },
  {
    method: 'POST',
    path: '/integration-products',
    sourceDecisionIds: ['integration-products-by-ids-read'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied ProductEditor product fallback through the Shopify resource port.',
  },
  {
    method: 'GET',
    path: '/overlay-lookup',
    sourceDecisionIds: ['overlay-lookup-read'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied ProductEditor premade overlay lookup with an empty optional catalog response.',
  },
  {
    method: 'POST',
    path: '/overlay-lookup',
    sourceDecisionIds: ['overlay-lookup-transparent-regions-write'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied ProductEditor transparent-region cache writes through scoped appData.',
  },
  {
    method: 'POST',
    path: '/template-usage',
    sourceDecisionIds: ['template-usage-check'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied ModalEditTemplate template reuse checks through scoped appData template snapshots.',
  },
  {
    method: 'GET',
    path: '/templates',
    sourceDecisionIds: ['template-list-read'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied ProductEditor merchant template picker list through scoped appData template snapshots.',
  },
  {
    method: 'GET',
    path: '/templates/:id',
    sourceDecisionIds: ['template-detail-read'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied ProductEditor selected-template detail read through scoped appData template snapshots.',
  },
  {
    method: 'POST',
    path: '/templates/:id/save',
    sourceDecisionIds: ['template-save-action'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied TemplateEditor save action through scoped appData template snapshots.',
  },
  {
    method: 'GET',
    path: '/option-sets',
    sourceDecisionIds: ['option-sets-list-read'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied TemplateEditor option-set initialization through scoped appData option-set snapshots.',
  },
  {
    method: 'GET',
    path: '/prompt-presets',
    sourceDecisionIds: ['prompt-presets-list-read'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied TemplateEditor prompt preset initialization with an explicit empty PageFly catalog.',
  },
  {
    method: 'POST',
    path: '/font-combination-suggestions',
    sourceDecisionIds: ['font-combination-suggestions-read'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied optional ProductEditor font-combination prefetch with an explicit empty result.',
  },
  {
    method: 'POST',
    path: '/files/query-media',
    sourceDecisionIds: ['shopify-media-files-query'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied ImageSelector Shopify media library reads through the Shopify resource port.',
  },
  {
    method: 'POST',
    path: '/files/upload',
    sourceDecisionIds: ['template-upload-files'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied ImageSelector base64 uploads through the Shopify staged-upload/S3 resource port.',
  },
  {
    method: 'POST',
    path: '/files/colour-guide-upload',
    sourceDecisionIds: ['colour-guide-upload-action'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied Colour Guide single-file base64 uploads through the S3 resource port.',
  },
  {
    method: 'POST',
    path: '/files/query-fonts',
    sourceDecisionIds: ['custom-font-files-query'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied typography custom-font queries with an explicit empty custom file page.',
  },
  {
    method: 'POST',
    path: '/files/query-masks',
    sourceDecisionIds: ['custom-mask-files-query'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied mask custom-file queries with an explicit empty custom file page.',
  },
  {
    method: 'GET',
    path: '/tutorials',
    sourceDecisionIds: ['tutorials-list-read'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied optional tutorial panel with an explicit empty PageFly tutorial catalog.',
  },
  {
    method: 'GET',
    path: '/user-journey',
    sourceDecisionIds: ['user-journey-read'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied editor trigger-tour completion reads through scoped appData user journeys.',
  },
  {
    method: 'POST',
    path: '/user-journey',
    sourceDecisionIds: ['user-journey-save-progress'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied editor trigger-tour skip/finish writes through scoped appData user journeys.',
  },
  {
    method: 'POST',
    path: '/templates-by-ids',
    sourceDecisionIds: ['template-get-by-ids'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied ProductEditor preview template reads through scoped appData template snapshots.',
  },
  {
    method: 'PUT',
    path: '/personalized-products/:id',
    sourceDecisionIds: ['integration-save-action'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied ProductEditor save form-action bridge.',
  },
  {
    method: 'POST',
    path: '/personalized-products/:id/publish',
    sourceDecisionIds: ['integration-publish-action'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied ProductEditor publish form-action bridge.',
  },
  {
    method: 'POST',
    path: '/personalized-products/:id/unpublish',
    sourceDecisionIds: ['integration-unpublish-action'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied ProductEditor unpublish form-action bridge.',
  },
  {
    method: 'POST',
    path: '/shared-template-integrations',
    sourceDecisionIds: ['integration-shared-templates-read'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied publish UI shared-template checks through scoped appData integrations.',
  },
  {
    method: 'POST',
    path: '/published-integrations-by-variant-ids',
    sourceDecisionIds: ['published-integrations-by-variant-ids-read'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied TemplateEditor republish modal integration lookup by active variant integration ids.',
  },
  {
    method: 'POST',
    path: '/published-integrations-by-template',
    sourceDecisionIds: ['published-integrations-by-template-read'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied TemplateEditor save modal lookup for published products using the current template.',
  },
  {
    method: 'GET',
    path: '/products-by-template',
    sourceDecisionIds: ['products-by-template-read'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied TemplateEditor integrated-products modal through Shopify resource and appData snapshots.',
  },
  {
    method: 'GET',
    path: '/charm-products',
    sourceDecisionIds: ['live-charm-products-read'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied charm picker live product hydration through the Shopify resource port.',
  },
  {
    method: 'POST',
    path: '/option-set-layer-usage',
    sourceDecisionIds: ['option-set-layer-usage-read'],
    status: 'source-mapped-adapter',
    notes: 'Backs copied TemplateEditor option-set usage checks through scoped layer snapshots.',
  },
] as const satisfies readonly TailorKitPageFlyApiRouteBridgeDecision[]
