export const EVENTS_TRACKING = {
  // Onboarding flow router (intent page + create-flow dropdown)
  ONBOARDING_INTENT_PAGE_SHOWN: 'onboarding_intent_page_shown',
  ONBOARDING_INTENT_SELECTED: 'onboarding_intent_selected',
  ONBOARDING_DEMO_CLICKED: 'onboarding_demo_clicked',
  CREATE_FLOW_INVOKED: 'create_flow_invoked',
  START_CREATE_LAYER: 'start_create_layer',
  NEXT_TOUR: 'next_tour',
  VIEW_ONBOARDING: 'view_onboarding',
  PREVIOUS_ONBOARDING: 'previous_onboarding',
  NEXT_STEP_APP_BLOCK: 'next_step_app_block',
  SKIP_ONBOARDING: 'skip_onboarding',
  CONTINUE_ONBOARDING: 'continue_onboarding',
  GO_TO_INTEGRATION: 'go_to_integration',
  VIEW_ON_SHOPIFY: 'view_on_shopify',
  CONNECT_WITH_PRINTIFY: 'connect_with_printify',
  IMPORT_MANUALLY: 'import_manually',
  START_ONBOARDING: 'start_onboarding',
  SELECT_ASSETS_FROM_ONBOARDING: 'select_assets_from_onboarding',
  COMPLETE_ONBOARDING: 'complete_onboarding',
  START_CREATE_PRODUCT: 'start_create_product',
  CREATE_NEW_PRODUCT_FROM_SELECTOR: 'create_new_product_from_selector',
  COMPLETE_CREATING_PRODUCT: 'complete_creating_product',
  CLOSE_PRODUCT_SELECTOR_MODAL: 'close_product_selector_modal',
  OPEN_DASHBOARD_INDEX: 'open_dashboard_index',
  OPEN_ANALYTICS_INDEX: 'open_analytics_index',
  OPEN_LIBRARIES_INDEX: 'open_libraries_index',
  OPEN_ORDERS_INDEX: 'open_orders_index',
  OPEN_PROVIDERS_INDEX: 'open_providers_index',
  OPEN_SETTINGS_ACCOUNT: 'open_settings_account',
  OPEN_SETTINGS_BILLING: 'open_settings_billing',
  OPEN_SETTINGS_PREFERENCES: 'open_settings_preferences',
  OPEN_TEMPLATES_INDEX: 'open_templates_index',
  ACHIEVE_SALE: 'achieve_sale',
  ACHIEVE_FIRST_CHARM_ORDER: 'achieve_first_charm_order',
  ADD_TEMPLATE_ELEMENT: 'add_template_element',
  UPLOAD_PSD_FILES: 'upload_psd_files',
  UPLOAD_BASE_IMAGE: 'upload_base_image',
  UPLOAD_BACKGROUND_IMAGE: 'upload_background_image',
  UPLOAD_MASK_LAYERS: 'upload_mask_layers',
  TOGGLE_CLIPPING_MASK: 'toggle_clipping_mask',
  OPEN_ADD_TEMPLATE_MODAL: 'open_add_template_modal',
  SELECT_TEMPLATE_FROM_TAILORKIT_TEMPLATES: 'select_template_from_tailorkit_templates',
  SELECT_TEMPLATE_FROM_YOUR_TEMPLATES: 'select_template_from_your_templates',
  ADD_PRINT_AREA_TEMPLATE: 'add_print_area_template',
  CHANGE_PRINT_AREA_TEMPLATE: 'change_print_area_template',
  SUBSCRIBE_PLAN: 'subscribe_plan',
  CHARGE_USAGE_FEES: 'charge_usage_fees',
  START_TRIAL: 'start_trial',
  TRIAL_ENDED: 'trial_ended',
  REINSTALLED_APP: 'reinstalled_app',
  ABANDON_TRIAL: 'abandon_trial',
  APPLY_PREMADE_MASK_LAYER: 'apply_premade_mask_layer',
  REMOVE_PREMADE_MASK_LAYER: 'remove_premade_mask_layer',
  AI_CHAT_FEEDBACK: 'ai_chat_feedback',
  AI_CHAT_SEND_MESSAGE: 'ai_chat_send_message',
  AI_CHAT_SUGGESTION_CLICK: 'ai_chat_suggestion_click',
  INSTALL_APP_BLOCK: 'install_app_block',
  INSTALL_APP_BLOCK_RETRY: 'install_app_block_retry',
  INSTALL_APP_BLOCK_FAILED: 'install_app_block_failed',
  INSTALL_APP_BLOCK_SUCCESS: 'install_app_block_success',
  INSTALL_APP_BLOCK_SUPPORT_AUTO_OPENED: 'install_app_block_support_auto_opened',
  INSTALL_APP_BLOCK_SUPPORT_ACCEPTED: 'install_app_block_support_accepted',
  INSTALL_APP_EMBED: 'install_app_embed',
  INSTALL_APP_EMBED_RETRY: 'install_app_embed_retry',
  VIEW_THEME_EDITOR: 'view_theme_editor',
  EDIT_DIMENSION_AND_RESOLUTION: 'edit_dimension_and_resolution',
  SAVE_PROVIDER_CONNECTION: 'save_provider_connection',
  EDITED_PROVIDER_PRODUCT_DETAIL: 'edited_provider_product_detail',
  IMPORT_PROVIDER_PRODUCTS_TO_SHOPIFY: 'import_provider_products_to_shopify',
  IMPORT_DUMMY_PRODUCTS_TO_SHOPIFY: 'import_dummy_products_to_shopify',
  CREATE_TEMPLATE_FROM_PERSONALIZED_PRODUCT: 'create_template_from_personalized_product',
  BACK_TO_PRODUCT: 'back_to_product',
  PUBLISH_MORE: 'publish_more',
  SAVE_PRODUCT: 'save_product',
  PUBLISH_PRODUCT: 'publish_product',
  UNPUBLISH_PRODUCT: 'unpublish_product',
  CLICK_APP_PROMOTION: 'click_app_promotion',
  CLICK_FEATURED_BANNER: 'click_featured_banner',
  GENERATE_MCP_ACCESS_TOKEN: 'generate_mcp_access_token',
  UNDO: 'undo',
  REDO: 'redo',
  BUILD_WITH_AI: 'build_with_ai',
  STOREFRONT_BUILD_WITH_AI: 'storefront_build_with_ai',
  OPEN_PERSONALIZED_PRODUCTS_INDEX: 'open_personalized_products_index',
  OPEN_PRODUCT_SELECTOR: 'open_product_selector',
  OPEN_CLIPART_SELECTOR: 'open_clipart_selector',
  SELECT_PRODUCT_SOURCE: 'select_product_source',
  EDIT_PROVIDER_PRODUCT: 'edit_provider_product',
  SELECT_PRINT_PROVIDER: 'select_print_provider',
  CHANGE_VARIANT_PROFIT: 'change_variant_profit',
  SELECT_EXISTING_PRODUCT: 'select_existing_product',
  STOREFRONT_UPLOAD_IMAGE: 'storefront_upload_image',
  STOREFRONT_ORDER: 'storefront_order',
  VIEW_PREVIEW_TEMPLATE: 'view_preview_template',
  AI_GENERATE_TEXT: 'ai_generate_text',
  AI_GENERATE_IMAGE: 'ai_generate_image',
  SELECT_OPTION_SET: 'select_option_set',
  UPLOAD_IMAGE_OPTION_SET: 'upload_image_option_set',
  VIEW_TUTORIAL: 'view_tutorial',
  PUBLISH_FIRST_PRODUCT_AFTER_APPROVE_CHARGE: 'publish_first_product_after_approve_charge',
  CLOSE_FIRST_PRODUCT_SETUP_MODAL_AFTER_APPROVE_CHARGE: 'close_first_product_setup_modal_after_approve_charge',
  OPEN_CHAT_BOT_AI_CREATE_PRODUCT: 'open_chat_bot_ai_create_product',
  AUTO_OPEN_AI_ONBOARDING_CHATBOT: 'auto_open_ai_onboarding_chatbot',
  AI_ONBOARDING_AUTO_SEND_PROMPT: 'ai_onboarding_auto_send_prompt',
  SELECT_OPTION_SET_DISPLAY_STYLE: 'select_option_set_display_style',
  CREATE_PERSONALIZED_PRODUCT: 'create_personalized_product',
  IMPORT_AND_CREATE_PERSONALIZED_PRODUCT: 'import_and_create_personalized_product',
  CLOSE_MODAL_IMPORT_AND_CREATE_PERSONALIZED_PRODUCT: 'close_modal_import_and_create_personalized_product',
  START_PERSONALIZING_PRODUCT: 'start_personalizing_product',
  SELECT_MODE: 'select_mode',
  TOGGLE_CHAT_BOT: 'toggle_chat_bot',
  CLOSE_CHAT_BOT: 'close_chat_bot',
  INSTALL_APP_WITHIN_5_MINUTES: 'install_app_within_5_minutes',
  CLICK_BLOG_PROMOTION: 'click_blog_promotion',
  CLICK_PREVIEW_PRODUCT_IMAGE: 'click_preview_product_image',
  HIDE_PREVIEW_PRODUCT_IMAGE: 'hide_preview_product_image',
  VIEW_EDITOR: 'view_editor',
  DISCARD_EDITOR: 'discard_editor',
  CLOSE_MODAL_SELECT_ASSETS_FROM_ONBOARDING: 'close_modal_select_assets_from_onboarding',
  SKIP_MODAL_SELECT_ASSETS_FROM_ONBOARDING: 'skip_modal_select_assets_from_onboarding',
  CHANGE_EDITOR_TAB: 'change_editor_tab',
  CHECK_PRODUCTS_MODAL: 'check_products_modal',
  // Publish to Earn (PTE) events
  PTE_MODAL_OPENED: 'pte_modal_opened',
  PTE_BADGE_UNLOCKED: 'pte_badge_unlocked',
  BULK_PRODUCT_ACTION: 'bulk_product_action',
  BULK_TEMPLATE_ACTION: 'bulk_template_action',
  // Clipart tracking events (Admin)
  CLIPART_VIEW: 'clipart_view',
  CLIPART_SELECT: 'clipart_select',
  CLIPART_CONVERT: 'clipart_convert',
  // Quick prompt tracking events (Admin)
  QUICK_PROMPT_VIEW: 'quick_prompt_view',
  QUICK_PROMPT_SELECT: 'quick_prompt_select',
  // Clipart tracking events (Storefront)
  STOREFRONT_CLIPART_VIEW: 'storefront_clipart_view',
  STOREFRONT_CLIPART_SELECT: 'storefront_clipart_select',
  // Quick prompt tracking events (Storefront)
  STOREFRONT_QUICK_PROMPT_VIEW: 'storefront_quick_prompt_view',
  STOREFRONT_QUICK_PROMPT_SELECT: 'storefront_quick_prompt_select',
  STOREFRONT_QUICK_PROMPT_CONVERT: 'storefront_quick_prompt_convert',
  // For modal Ask Why Only Save Not Publish
  USER_ONLY_TEST: 'user_only_test',
  // MockupWizard tracking events
  MOCKUP_WIZARD_STARTED: 'mockup_wizard_started',
  MOCKUP_WIZARD_PROCESSED: 'mockup_wizard_processed',
  MOCKUP_WIZARD_APPLIED: 'mockup_wizard_applied',
  MOCKUP_WIZARD_CLOSED: 'mockup_wizard_closed',
  // VectorWizard tracking events
  VECTOR_WIZARD_STARTED: 'vector_wizard_started',
  VECTOR_WIZARD_PROCESSED: 'vector_wizard_processed',
  VECTOR_WIZARD_APPLIED: 'vector_wizard_applied',
  VECTOR_WIZARD_CLOSED: 'vector_wizard_closed',
  // VectorEditor tracking events
  VECTOR_EDITOR_STARTED: 'vector_editor_started',
  VECTOR_EDITOR_PROCESSED: 'vector_editor_processed',
  VECTOR_EDITOR_APPLIED: 'vector_editor_applied',
  VECTOR_EDITOR_CLOSED: 'vector_editor_closed',
  // Checkbox Feature Events
  CHECKBOX_LIST_VIEWED: 'checkbox_list_viewed',
  CHECKBOX_CREATED: 'checkbox_created',
  CHECKBOX_UPDATED: 'checkbox_updated',
  CHECKBOX_DELETED: 'checkbox_deleted',
  CHECKBOX_DUPLICATED: 'checkbox_duplicated',
  CHECKBOX_ACTIVATED: 'checkbox_activated',
  CHECKBOX_DEACTIVATED: 'checkbox_deactivated',
  CHECKBOX_BULK_DELETED: 'checkbox_bulk_deleted',
  CHECKBOX_BULK_ACTIVATED: 'checkbox_bulk_activated',
  CHECKBOX_BULK_DEACTIVATED: 'checkbox_bulk_deactivated',
  CHECKBOX_BULK_DUPLICATED: 'checkbox_bulk_duplicated',
  // Checkbox Onboarding Events
  CHECKBOX_ONBOARDING_STARTED: 'checkbox_onboarding_started',
  CHECKBOX_ONBOARDING_STEP_COMPLETED: 'checkbox_onboarding_step_completed',
  CHECKBOX_ONBOARDING_STEP_SKIPPED: 'checkbox_onboarding_step_skipped',
  CHECKBOX_ONBOARDING_COMPLETED: 'checkbox_onboarding_completed',
  CHECKBOX_ONBOARDING_EXITED: 'checkbox_onboarding_exited',
  // Setup Guide Events
  SETUP_GUIDE_CREATE_TEMPLATE: 'setup_guide_create_template',
  SETUP_GUIDE_PUBLISH_PRODUCT: 'setup_guide_publish_product',
  SETUP_GUIDE_INSTALL_APP_BLOCK: 'setup_guide_install_app_block',
  SETUP_GUIDE_ENABLE_APP_EMBED: 'setup_guide_enable_app_embed',
  // Pricing Page Events
  PRICING_PAGE_VIEW: 'pricing_page_view',
  PRICING_SELECT_PLAN: 'pricing_select_plan',
  PRICING_CONFIRM_PLAN: 'pricing_confirm_plan',
  PRICING_CHECKOUT_RESULT: 'pricing_checkout_result',
  PRICING_DISCOUNT_CODE_APPLIED: 'pricing_discount_code_applied',
  PRICING_CALCULATOR_USED: 'pricing_calculator_used',
  PRICING_ROI_CALCULATOR_USED: 'pricing_roi_calculator_used',
  PRICING_SOCIAL_PROOF_CLICKED: 'pricing_social_proof_clicked',
  PRICING_FEATURE_TABLE_VIEWED: 'pricing_feature_table_viewed',
  PRICING_SECTION_TOGGLED: 'pricing_section_toggled',
  PRICING_CONTACT_SUPPORT: 'pricing_contact_support',
  PRICING_FAQ_TOGGLED: 'pricing_faq_toggled',
  // Subscriber Billing surfaces (Phase 5 of pricing-page-subscriber-mode)
  BILLING_PAGE_VIEW: 'billing_page_view',
  BILLING_ACTION_CLICK: 'billing_action_click',
  SUBSCRIBER_UPGRADE_INTENT: 'subscriber_upgrade_intent',
  // Need Help Card Events
  BOOK_DEMO_CALL: 'book_demo_call',
  // Feature adoption tracking (unified heartbeat event)
  FEATURE_USED: 'feature_used',
  // Post-publish Checklist Events
  POST_PUBLISH_CHECKLIST_SHOWN: 'post_publish_checklist_shown',
  POST_PUBLISH_CHECKLIST_ITEM_CLICKED: 'post_publish_checklist_item_clicked',
  POST_PUBLISH_CHECKLIST_DISMISSED: 'post_publish_checklist_dismissed',
  POST_PUBLISH_CHECKLIST_SOCIAL_SHARE: 'post_publish_checklist_social_share',
  // App Store Review Card Events
  REVIEW_CARD_SHOWN: 'review_card_shown',
  REVIEW_CARD_WRITE_REVIEW_CLICKED: 'review_card_write_review_clicked',
  REVIEW_CARD_NATIVE_RESULT: 'review_card_native_result',
  REVIEW_CARD_NOT_NOW_CLICKED: 'review_card_not_now_clicked',
  REVIEW_CARD_NEED_HELP_CLICKED: 'review_card_need_help_clicked',
  REVIEW_CARD_DISMISSED: 'review_card_dismissed',
  REVIEW_FALLBACK_APP_STORE_OPENED: 'review_fallback_app_store_opened',
}

export const EVENTS_PARAMETERS_NAME = {
  SELECTION: 'selection',
  DISPLAY_STYLE: 'display_style',
  CURRENT_STEP: 'current_step',
  TYPE: 'type',
  VALUE: 'value',
  ID: 'id',
  COMPLETION_MINUTES: 'completion_minutes',
  CREATION_MINUTES: 'creation_minutes',
  PUBLISHING_MINUTES: 'publishing_minutes',
  APP_GENERATED_REVENUE: 'app_generated_revenue',
  ELEMENT_TYPE: 'element_type',
  NUM_FILES: 'number_of_files',
  PROCESSING_MINUTES: 'processing_minutes',
  NEW_VALUE: 'new_value',
  PRODUCT_NAME: 'product_name',
  PRODUCT_TYPE: 'product_type',
  PRODUCT_VENDOR: 'product_vendor',
  PRINT_AREA_NAME: 'print_area_name',
  PRINT_AREA_DIMENSION: 'print_area_dimension',
  REVENUE_TIER: 'revenue_tier',
  TIER_USAGE_FEES: 'tier_usage_fees',
  USAGE_FEES_AFTER_DISCOUNT: 'usage_fees_after_discount',
  CHARGED_ADDITIONAL_USAGE_FEES: 'charged_additional_usage_fees',
  TRIAL_ENDS_ON: 'trial_ends_on',
  TRIAL_DAYS: 'trial_days',
  PREMADE_MASK_LAYER_ALIAS: 'premade_mask_layer_alias',
  CREATE_TEMPLATE_FROM: 'create_template_from',
  CREATE_LAYER_FROM: 'create_layer_from',
  NEW_WIDTH: 'new_width',
  NEW_HEIGHT: 'new_height',
  NEW_RESOLUTION: 'new_resolution',
  MEASUREMENT_UNIT: 'measurement_unit',
  NUM_VARIANTS: 'number_of_variants',
  NUM_PRODUCTS: 'number_of_products',
  NUM_MOCKUPS: 'number_of_mockups',
  NUM_PRINT_AREAS: 'number_of_print_areas',
  NUM_DAYS_AFTER_INSTALL: 'number_of_days_after_install',
  APP_PROMOTION: 'app_promotion',
  FEATURED_BANNER: 'featured_banner',
  AI_GENERATE_FROM: 'ai_generate_from',
  UPLOAD_IMAGE_FROM: 'upload_image_from',
  TUTORIAL_NAME: 'tutorial_name',
  START_PERSONALIZING_PRODUCT_FROM: 'start_personalizing_product_from',
  BLOG_PROMOTION: 'blog_promotion',
  // Clipart & Quick Prompt tracking parameters
  CLIPART_ID: 'clipart_id',
  CLIPART_NAME: 'clipart_name',
  CLIPART_CATEGORY: 'clipart_category',
  CLIPART_IDS: 'clipart_ids',
  CLIPART_COUNT: 'clipart_count',
  SOURCE_COMPONENT: 'source_component',
  PROMPT_NAME: 'prompt_name',
  PROMPT_ALIAS: 'prompt_alias',
  PROMPT_TYPE: 'prompt_type',
  PROMPT_COUNT: 'prompt_count',
  BATCH_ID: 'batch_id',
  SESSION_ID: 'session_id',
  TIME_TO_SELECT_SECONDS: 'time_to_select_seconds',
  SELECTION_POSITION: 'selection_position',
  // MockupWizard/VectorWizard/VectorEditor Parameters
  ORIGINAL_IMAGE_URL: 'original_image_url',
  GENERATED_MASK_URL: 'generated_mask_url',
  GENERATED_VECTOR_URL: 'generated_vector_url',
  SAVED_VECTOR_URL: 'saved_vector_url',
  // Checkbox Parameters
  CHECKBOX_ID: 'checkbox_id',
  CHECKBOX_TITLE: 'checkbox_title',
  CHECKBOX_COUNT: 'checkbox_count',
  CHECKBOX_STATUS: 'checkbox_status',
  CHECKBOX_PLACEMENT: 'checkbox_placement',
  CHECKBOX_TRIGGER_TYPE: 'checkbox_trigger_type',
  CHECKBOX_SOURCE: 'checkbox_source',
  ONBOARDING_STEP: 'onboarding_step',
  // Pricing tracking parameters
  PLAN_NAME: 'plan_name',
  PLAN_ALIAS: 'plan_alias',
  PLAN_PRICE: 'plan_price',
  DISCOUNT_CODE: 'discount_code',
  DISCOUNT_AMOUNT: 'discount_amount',
  DISCOUNT_STATUS: 'discount_status',
  TOTAL_PRICE: 'total_price',
  ORDER_COUNT: 'order_count',
  IS_MIGRATION_USER: 'is_migration_user',
  HAS_ACTIVE_PLAN: 'has_active_plan',
  CURRENT_PLAN_NAME: 'current_plan_name',
  SECTION_NAME: 'section_name',
  CHECKOUT_OUTCOME: 'checkout_outcome',
  // Subscriber billing-page params
  ACTION: 'action',
  EXPANDED: 'expanded',
  CREDIT_STATE: 'credit_state',
  FROM_PLAN: 'from_plan',
  TO_PLAN: 'to_plan',
  // Feature adoption tracking parameters
  FEATURE_NAME: 'feature_name',
  FEATURE_ACTION: 'feature_action',
  LIFECYCLE_STAGE: 'lifecycle_stage',
  DAYS_SINCE_INSTALL: 'days_since_install',
  ENTRY_POINT: 'entry_point',
  TASK_SUCCESS: 'task_success',
  DURATION_SECONDS: 'duration_seconds',
  ABANDON_STEP: 'abandon_step',
  ERROR_TYPE: 'error_type',
}

/**
 * Usage fee types for charge_usage_fees event
 * Extracted to separate constant for type safety
 */
export const USAGE_FEE_TYPES = {
  ORDER_OVERAGE: 'order_overage_fees',
  AI_CREDIT: 'ai_credit_fees',
} as const
