export const MODALS = {
  DASHBOARD: {
    ONBOARDING_DASHBOARD_MODAL_ID: 'ONBOARDING_DASHBOARD_MODAL_ID',
    FIRST_PRODUCT_SETUP_MODAL_ID: 'FIRST_PRODUCT_SETUP_MODAL_ID',
    INSTALL_TAILORKIT_APP_BLOCK_MODAL_ID: 'INSTALL_TAILORKIT_APP_BLOCK_MODAL_ID',
    PRODUCT_SELECTOR_MODAL_ID: 'PRODUCT_SELECTOR_MODAL_ID',
    CLIPART_SELECTOR_MODAL_ID: 'CLIPART_SELECTOR_MODAL_ID',
    CLIPART_SHOWCASE_MODAL_ID: 'CLIPART_SHOWCASE_MODAL_ID',
  },
} as const
