// Direct Vite config is kept for local single-app debugging.
// CI and repo scripts use scripts/build.mjs so multiple internal app assets can build independently.
import path from 'path'
import { fileURLToPath } from 'url'
import { defineConfig, type UserConfig } from 'vite'
import { discoverThemeSurfaceApps, selectThemeSurfaceApps } from './scripts/theme-surface-loader.mjs'

const extensionRoot = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(extensionRoot, '../..')
const apps = selectThemeSurfaceApps(discoverThemeSurfaceApps(repoRoot), process.env.APP_PLATFORM_APP_ID, {
  includeOnDemand: process.env.APP_PLATFORM_BUILD_ALL === 'true',
})
const javascriptAssets = apps.flatMap(app =>
  (app.themeSurfaces.assets || [])
    .filter(asset => asset.kind === 'javascript')
    .map(asset => ({
      appId: app.themeSurfaces.appId,
      entry: path.resolve(repoRoot, app.sourceRoot, asset.source),
      generatedName: asset.generatedName,
    }))
)

if (javascriptAssets.length !== 1) {
  throw new Error(
    'Direct vite build needs exactly one JavaScript asset. Use `node scripts/build.mjs` for multi-app builds, '
      + 'or set APP_PLATFORM_APP_ID for single-app debugging.'
  )
}

const javascriptAsset = javascriptAssets[0]
const generatedHeader = `/* GENERATED BY app-platform. Source: ${path.relative(
  repoRoot,
  javascriptAsset.entry
)}. Do not edit directly. */`

function appGlobalName(appId: string): string {
  return `${appId.replace(/(^|-)([a-z0-9])/g, (_, _dash, letter) => letter.toUpperCase())}StorefrontRuntime`
}

export default defineConfig({
  build: {
    assetsDir: '',
    emptyOutDir: false,
    minify: false,
    sourcemap: false,
    target: 'es2019',
    outDir: '../pagefly-theme-helper/assets',
    lib: {
      entry: javascriptAsset.entry,
      fileName: () => javascriptAsset.generatedName,
      formats: ['iife'],
      name: appGlobalName(javascriptAsset.appId),
    },
    rollupOptions: {
      output: {
        inlineDynamicImports: true,
      },
      plugins: [
        {
          name: 'app-platform-generated-header',
          generateBundle(_outputOptions, bundle) {
            const file = bundle[javascriptAsset.generatedName]
            if (file && 'code' in file) {
              file.code = `${generatedHeader}\n${file.code}`
            }
          },
        },
      ],
    },
  },
}) as UserConfig
