/* eslint-disable max-lines */
import { h, render } from 'preact'
import type { SuggestionList } from '../../components/commons/ai-generate/suggestion-list'
import type Button from '../../components/commons/button'
import Tooltip from '../../components/commons/tooltip'
import GenerateImagePopover from '../../components/preact/commons/ai-generate/GenerateImagePopover'
import type { TailorKitProductPersonalizer } from '../../components/product-personalizer'
import { APP_PROXY_PATH } from '../../constants'
import { STORE_FRONT_ACTION } from '../../constants/app-actions'
import { isJSON } from '../../fns/is-json'
import { createSvgIcon, ERROR_ICON_PATH } from '../../icons/editor-icons'
import { fetchWithAdminContext } from '../../libraries/fetchWithAdminContext'
import { Transmitter } from '../../libraries/transmitter'
import type { Layer, LayerIntegration } from '../../type'
import { findViewAndSwitchTo } from '../../utils/query-views'
import { processUploadedImage } from './image-editor/data-processing'
import { showImageEditorModal } from './image-editor/modal'
import type { KonvaEditorState } from './image-editor/types/editor-types'
import { showErrorModal, uploadImageToServer, urlToFile } from './image-editor/upload-service'
import { checkIfButtonIsDisabled, getMaskOption, getTransformerConfig, hasReachedLimit } from './upload-image'
import {
  extractFilterPresetIdFromSvg,
  extractFilterPresetParamsFromSvg,
  extractFillStrokeFromSvg,
  getSvgContent,
} from './ai-generation-helpers'
import { loadImage } from '../../utils/canvas'
import { sessionStorage } from '../../utils/sessionStorage'
import { hideAiGenerationUI, markAiCreditsExhausted } from '../../utils/ai-credits'

const DEFAULT_NUMBER_OF_IMAGES = 1
const MAX_IMAGE_GENERATED_BY_AI_USAGE = 3

/** Generation mode - 'image' for raster images, 'vector' for SVG */
export type GenerationMode = 'image' | 'vector'

// Helper function to track storefront events via app proxy
const trackStorefrontEvent = (eventName: string, properties: Record<string, any>) => {
  const formData = new FormData()
  formData.append('action', STORE_FRONT_ACTION.TRACK_EVENT)
  formData.append('eventName', eventName)
  formData.append('properties', JSON.stringify(properties))

  fetch(`${APP_PROXY_PATH}/app_proxy/storefront`, {
    method: 'POST',
    body: formData,
  }).catch(console.error)
}

export type TGeneratedImage = {
  alt: string
  contentType: string
  filename: string
  originalSource: string
  loading?: boolean
}

const setImagesGeneratedByAi = (layerId: string, images: TGeneratedImage[]) => {
  if (!layerId) return

  try {
    // Use sessionStorage for AI-generated images to prevent stale data issues
    sessionStorage.setItem(`tlk_images_generated_by_ai_${layerId}`, JSON.stringify(images))
  } catch (storageError) {
    console.warn("sessionStorage is not available, possibly in incognito mode. Images generated by AI won't persist.")
  }
}

const getImagesGeneratedByAi = (layerId: string): TGeneratedImage[] => {
  // Use sessionStorage for AI-generated images to prevent stale data issues
  const imagesGeneratedByAi = sessionStorage.getItem(`tlk_images_generated_by_ai_${layerId}`)
  return imagesGeneratedByAi && isJSON(imagesGeneratedByAi) ? JSON.parse(imagesGeneratedByAi) : []
}

/**
 * Static registry to track active handlers per layer - used for cleanup
 */
const activeHandlers = new Map<string, GenerateImageHandler>()

/**
 * Class that handles image generation with AI functionality
 */
export class GenerateImageHandler {
  private instance: TailorKitProductPersonalizer | null = null
  private activatorContainer: HTMLElement | null = null
  private activator: HTMLElement | null = null
  private layer: Layer | null = null
  private fieldset: HTMLFieldSetElement | null = null
  private contentWrapper: HTMLElement | null = null
  private suggestionList: SuggestionList | null = null
  private imagesGeneratedByAi: TGeneratedImage[] = []
  private lastGeneratedPrompt: string | null = null
  private generateButton: Button | null = null
  private replaceImage: boolean = false
  private optionIdToReplace: string = ''
  private selectedReferenceUrls: string[] = []
  private inlineMode: boolean = false
  private limitReached: boolean = false
  private isSubscribed: boolean = false
  private mode: GenerationMode = 'image'

  /**
   * @param activator - The activator element
   * @param instance - The TailorKitProductPersonalizer instance
   * @param replaceImage - Whether replacing an existing image
   * @param optionIdToReplace - The option ID to replace
   * @param mode - Generation mode ('image' for raster, 'vector' for SVG)
   */
  constructor(
    activator: HTMLElement,
    instance: TailorKitProductPersonalizer,
    replaceImage: boolean,
    optionIdToReplace: string,
    mode: GenerationMode = 'image'
  ) {
    const isInlineActivator = activator.classList.contains('emtlkit--generate-image-with-ai')
    const activatorContainer = (
      isInlineActivator ? activator : (activator.closest('.emtlkit--popover-container') as HTMLElement | null)
    ) as HTMLElement | null
    const fieldset = activator.closest('fieldset') as HTMLFieldSetElement

    // Find the relevant layer integration and layer
    const layerIntegration = instance.productPersonalizer?.lis?.find(
      (li: LayerIntegration) => li.data?.printAreaId === fieldset?.dataset?.printAreaId
    )
    const layer = layerIntegration?.data?.ls.find((l: Layer) => l.i === fieldset?.dataset?.layerId)

    // Check if generated by AI limit has been reached (skip check if replacing an existing image)
    const limitReached
      = !replaceImage && hasReachedLimit(layer?.osl, MAX_IMAGE_GENERATED_BY_AI_USAGE, 'image_generated_by_ai')

    if (limitReached && !isInlineActivator) {
      activator.classList.add('emtlkit-button-disabled')

      new Tooltip(activator, {
        content: `You have uploaded ${MAX_IMAGE_GENERATED_BY_AI_USAGE} images. Click Edit button below an image to replace it.`,
        trigger: 'hover',
      })

      activator.setAttribute('disabled', 'true')
      return
    }

    this.inlineMode = Boolean(activatorContainer?.classList.contains('emtlkit--generate-image-with-ai'))
    this.activatorContainer = activatorContainer
    this.activator = isInlineActivator ? activatorContainer : activator
    this.instance = instance
    this.layer = layer
    this.fieldset = fieldset
    this.suggestionList = null
    this.imagesGeneratedByAi = getImagesGeneratedByAi(layer?.i)
    this.lastGeneratedPrompt = null
    this.generateButton = null
    this.replaceImage = replaceImage
    this.optionIdToReplace = optionIdToReplace
    this.limitReached = limitReached
    this.mode = mode
  }

  /**
   * Get fresh layer data from instance
   */
  private getFreshLayerData(): Layer | undefined {
    const layerIntegration = this.instance?.productPersonalizer?.lis?.find(
      (li: LayerIntegration) => li.data?.printAreaId === this.fieldset?.dataset?.printAreaId
    )
    return layerIntegration?.data?.ls.find((l: Layer) => l.i === this.fieldset?.dataset?.layerId)
  }

  /**
   * Check if AI image generation limit has been reached using fresh layer data
   */
  private hasReachedAiImageLimit(): boolean {
    if (this.replaceImage) return false

    const freshLayer = this.getFreshLayerData()
    return hasReachedLimit(freshLayer?.osl, MAX_IMAGE_GENERATED_BY_AI_USAGE, 'image_generated_by_ai')
  }

  /**
   * Handler for 'tailorkit-set-options' event to sync inline generator state
   */
  private handleOptionsChange = (): void => {
    if (!this.inlineMode || !this.layer?.i || !this.contentWrapper) return

    // Update limitReached with fresh data and re-render component
    const newLimitReached = this.hasReachedAiImageLimit()
    if (newLimitReached !== this.limitReached) {
      this.limitReached = newLimitReached
      this.renderGeneratorComponent()
    }
  }

  /**
   * Subscribe to options change event (prevents duplicate subscriptions)
   */
  private subscribeToOptionsChange(): void {
    if (this.isSubscribed) return

    // Cleanup previous handler for this layer if exists
    const layerId = this.layer?.i
    if (layerId) {
      const existingHandler = activeHandlers.get(layerId)
      if (existingHandler && existingHandler !== this) {
        existingHandler.destroy()
      }
      activeHandlers.set(layerId, this)
    }

    Transmitter.listen('tailorkit-set-options', this.handleOptionsChange)
    this.isSubscribed = true
  }

  /**
   * Unsubscribe from options change event
   */
  private unsubscribeFromOptionsChange(): void {
    if (!this.isSubscribed) return

    Transmitter.remove('tailorkit-set-options', this.handleOptionsChange)
    this.isSubscribed = false
  }

  /**
   * Cleanup handler and remove event listeners
   */
  public destroy(): void {
    this.unsubscribeFromOptionsChange()

    const layerId = this.layer?.i
    if (layerId && activeHandlers.get(layerId) === this) {
      activeHandlers.delete(layerId)
    }
  }

  /**
   * Render or re-render the GenerateImagePopover component
   */
  private renderGeneratorComponent(): void {
    if (!this.layer?.i || !this.contentWrapper) return

    const generativeOptions = {
      ...(this.layer.s.generativeOptions || {}),
    } as any
    const imageUploaderOptions = this.layer.s.imageUploaderOptions
    const disabledMessage = `You have uploaded ${MAX_IMAGE_GENERATED_BY_AI_USAGE} images. Click Edit button below an image to replace it.`

    render(
      h(GenerateImagePopover, {
        layerId: this.layer.i,
        layer: this.layer,
        generativeOptions,
        allowCustomerToUseReferenceImage: imageUploaderOptions?.allowCustomerToUseReferenceImage,
        enabledQuickPrompts: imageUploaderOptions?.enabledQuickPrompts,
        enabledTemplateTypes: imageUploaderOptions?.enabledTemplateTypes,
        enabledVisualStyles: imageUploaderOptions?.enabledVisualStyles,
        enabledContentThemes: imageUploaderOptions?.enabledContentThemes,
        allowCustomerToUseQuickPrompts: imageUploaderOptions?.allowCustomerToUseQuickPrompts,
        allowCustomerToUseTemplateTypes: imageUploaderOptions?.allowCustomerToUseTemplateTypes,
        allowCustomerToUseVisualStyles: imageUploaderOptions?.allowCustomerToUseVisualStyles,
        allowCustomerToUseContentThemes: imageUploaderOptions?.allowCustomerToUseContentThemes,
        autoRemoveSolidWhiteBackground: imageUploaderOptions?.autoRemoveSolidWhiteBackground,
        disabledGenerate: this.limitReached && !this.replaceImage,
        disabledGenerateMessage: disabledMessage,
        showTitle: !this.inlineMode,
        onGenerate: this.handleGenerate,
      }),
      this.contentWrapper
    )
  }

  /**
   * Handle generate callback from GenerateImagePopover
   */
  private handleGenerate = async (
    promptValue: string,
    referenceFiles: File[],
    selectedRatio: string,
    templateType?: string,
    visualStyle?: string,
    contentTheme?: string
  ): Promise<void> => {
    // Check limit with fresh data before generating
    if (this.hasReachedAiImageLimit()) {
      this.renderErrorMessage(
        `You have uploaded ${MAX_IMAGE_GENERATED_BY_AI_USAGE} images. Click Edit button below an image to replace it.`
      )
      return
    }

    const images = await this.onGenerate(
      promptValue,
      referenceFiles,
      selectedRatio,
      templateType,
      visualStyle,
      contentTheme
    )

    // Auto-select the first generated image (skip suggestion list for faster UX)
    if (images && images.length > 0) {
      await this.onSelectOption(images[0])
    }
  }

  /** Ensure a stable inner root for inline rendering to avoid race/clears */
  private ensureInlineRoot(): HTMLElement {
    const host = this.activatorContainer as HTMLElement
    let root = host.querySelector(':scope > .emtlkit--ai-root') as HTMLElement | null
    if (!root) {
      root = document.createElement('div')
      root.className = 'emtlkit--ai-root'
      host.appendChild(root)
    }
    // Clear only our root, not the whole host element
    root.innerHTML = ''
    return root
  }

  private mountGeneratorContent(): boolean {
    if (!this.layer || !this.layer?.i || !this.activatorContainer) return false

    const container = this.inlineMode ? this.ensureInlineRoot() : document.createElement('div')

    this.contentWrapper = container
    this.renderGeneratorComponent()

    // Ensure the accordion/details wrapper is open so content is visible (not height:0)
    if (this.inlineMode && this.activatorContainer) {
      const details = this.activatorContainer.closest('details') as HTMLDetailsElement | null
      if (details && !details.open) details.open = true
    }

    return true
  }

  public mountInlineGenerator(): void {
    if (!this.inlineMode || !this.activatorContainer) return

    const mounted = this.mountGeneratorContent()
    if (!mounted) return

    // Subscribe to options change event to sync button state (e.g., after image deletion)
    this.subscribeToOptionsChange()
  }

  private focusInlineGenerator(): void {
    if (!this.inlineMode || !this.activatorContainer) return
    this.activatorContainer.scrollIntoView({ behavior: 'smooth', block: 'start' })
  }

  /** Handle image generation */
  private async onGenerate(
    promptValue: string,
    referenceInputs: (File | string)[] = [],
    selectedRatio: string,
    templateType?: string,
    visualStyle?: string,
    contentTheme?: string
  ): Promise<TGeneratedImage[]> {
    if (!this.contentWrapper) return []

    const defaultErrorMessage = 'An error occurred while generating the image. Please try again after few seconds.'
    let errorMessage = ''
    let images: TGeneratedImage[] = []

    // Allow generation if there's a prompt OR (visual style + reference images)
    const hasValidInput = promptValue || (visualStyle && referenceInputs?.length)
    if (!hasValidInput) {
      errorMessage = 'Please enter a prompt or select a visual style with a reference image'
    }

    if (!selectedRatio) {
      errorMessage = 'Please select a ratio'
    }

    if (hasValidInput && selectedRatio && this.layer?.s) {
      let imageSkeleton: HTMLDivElement | null = null
      let loadingIndicator: HTMLDivElement | null = null

      // Initialize or update suggestion list
      const suggestionsContainer = this.contentWrapper.querySelector('.emtlkit--generate-image-wrapper') as HTMLElement

      if (!this.suggestionList) {
        loadingIndicator = document.createElement('div')
        loadingIndicator.className = 'emtlkit--loading-indicator'
        loadingIndicator.innerHTML = 'Generating images can take up to 30 seconds.'
        suggestionsContainer.appendChild(loadingIndicator)

        imageSkeleton = document.createElement('div')
        imageSkeleton.className = 'emtlkit--image-skeleton'
        suggestionsContainer.appendChild(imageSkeleton)
      }

      const url = `${APP_PROXY_PATH}/app_proxy/storefront`
      const formData = new FormData()
      const generateAction
        = this.mode === 'vector' ? STORE_FRONT_ACTION.GENERATE_VECTOR : STORE_FRONT_ACTION.GENERATE_IMAGE
      formData.append('action', generateAction)
      // Persist references for future regenerations
      const uploadedReferenceUrls: string[] = []
      if (Array.isArray(referenceInputs) && referenceInputs.length) {
        for (const ref of referenceInputs) {
          if (typeof ref === 'string') {
            if (/^https?:\/\//i.test(ref)) uploadedReferenceUrls.push(ref)
          } else {
            try {
              const res = await uploadImageToServer(ref)
              if (res?.success && res.url) uploadedReferenceUrls.push(res.url)
            } catch (e) {
              console.error('Failed to upload reference image', e)
            }
          }
        }
      }
      this.selectedReferenceUrls = uploadedReferenceUrls

      const effectiveReferenceUrls = this.selectedReferenceUrls.length > 0 ? this.selectedReferenceUrls : []

      // Extract style data from layer's original SVG for vector generation
      // This allows the backend to apply the same filter and fill/stroke to the generated vector
      let filterPresetId: string | undefined
      let filterPresetParams: Record<string, number> | undefined
      let fill: string | undefined
      let stroke: string | undefined
      let strokeWidth: number | undefined

      if (this.mode === 'vector' && this.layer.u) {
        const svgContent = await getSvgContent(this.layer.u)
        if (svgContent) {
          filterPresetId = extractFilterPresetIdFromSvg(svgContent) ?? undefined
          filterPresetParams = extractFilterPresetParamsFromSvg(svgContent) ?? undefined
          const fillStroke = extractFillStrokeFromSvg(svgContent)
          if (fillStroke) {
            fill = fillStroke.fill
            stroke = fillStroke.stroke
            strokeWidth = fillStroke.strokeWidth
          }
        }
      }

      const jsonData: Record<string, any> = {
        templateType,
        visualStyle,
        contentTheme,
        action: generateAction,
        prompt: promptValue,
        aspectRatio: selectedRatio,
        referenceImageUrls: effectiveReferenceUrls,
        numberGeneratedImages: DEFAULT_NUMBER_OF_IMAGES,
        solidWhiteBackgroundRemoval: this.layer.s.imageUploaderOptions?.autoRemoveSolidWhiteBackground ?? false,
      }

      // Add style transfer data for vector generation (filter preset + fill/stroke)
      if (filterPresetId) jsonData.filterPresetId = filterPresetId
      if (filterPresetParams) jsonData.filterPresetParams = filterPresetParams
      if (fill) jsonData.fill = fill
      if (stroke) jsonData.stroke = stroke
      if (strokeWidth) jsonData.strokeWidth = strokeWidth

      formData.append('jsonData', JSON.stringify(jsonData))

      try {
        // Save the current prompt for later comparison
        this.lastGeneratedPrompt = promptValue

        const res = await fetchWithAdminContext(url, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' },
          mode: 'no-cors',
          body: formData,
        })

        // Handle non-OK HTTP responses
        if (!res.ok) {
          const errorText = await res.text().catch(() => '')
          throw new Error(errorText || `Request failed with status ${res.status}`)
        }

        let response
        try {
          response = await res.json()
        } catch (parseError) {
          throw new Error('Failed to parse server response. Please try again.')
        }

        if (!response.success) {
          // Handle AI credits exhausted - hide all AI generation UI
          if (response.code === 'AI_CREDITS_EXHAUSTED') {
            markAiCreditsExhausted()
            hideAiGenerationUI()
            throw new Error(response.error || 'AI credits exhausted')
          }
          throw new Error(response.message || defaultErrorMessage)
        }

        // Handle vector response format (returns svgUrl directly)
        if (this.mode === 'vector') {
          const svgUrl = response.svgUrl || response.svgDataUri
          if (!svgUrl) {
            throw new Error('Vector generation succeeded but did not return SVG data.')
          }

          const filename = `ai-vector-${Date.now()}.svg`
          images = [
            {
              alt: filename,
              contentType: 'image/svg+xml',
              filename,
              originalSource: svgUrl,
            },
          ]
        } else {
          // Handle image response format (returns data.uploadedFiles)
          const result = response

          if (!result || !result.data) {
            throw new Error('Upload request succeeded but did not return valid file data.')
          }

          if (result.data?.errors || result.data?.errorFiles?.length) {
            throw new Error(result.data.errors || 'Some images failed to upload')
          }

          const uploadedFiles = result.data.uploadedFiles || []
          images = uploadedFiles.map((file: any) => ({
            alt: file.alt,
            contentType: file.__typename,
            filename: file.alt,
            originalSource: file.image.originalSrc,
          }))
        }

        // Save the images to localStorage to keep the images generated by AI before
        if (this.layer?.i) {
          const imagesGeneratedByAi = getImagesGeneratedByAi(this.layer?.i)
          const _images = [...images, ...imagesGeneratedByAi]
          setImagesGeneratedByAi(this.layer?.i, _images)
          this.imagesGeneratedByAi = _images
        }

        if (this.suggestionList) {
          const currentSuggestions = (this.suggestionList.getSuggestions() as TGeneratedImage[]) || []
          this.suggestionList.update([...currentSuggestions.filter(suggestion => !suggestion.loading), ...images])
        }

        // Preload the first image
        const firstImage = images[0]
        if (firstImage) {
          await loadImage(firstImage.originalSource)
        }

        Transmitter.trigger('tailorkit-storefront-usage', { feature: 'AI_GEN_IMAGE' })

        // Track quick prompt conversion when image is successfully generated with prompt presets
        if (templateType || visualStyle || contentTheme) {
          try {
            const promptsUsed: string[] = []
            if (templateType) promptsUsed.push(templateType)
            if (visualStyle) promptsUsed.push(visualStyle)
            if (contentTheme) promptsUsed.push(contentTheme)

            const convertEventProps = {
              prompt_names: promptsUsed,
              prompt_type: 'ai_image_generation',
              source_component: 'storefront_generate_image',
              images_generated_count: images.length,
              session_id: (window as any).TailorKitPersonalizationSession?.sessionId || '',
            }
            trackStorefrontEvent('storefront_quick_prompt_convert', convertEventProps)
          } catch (e) {
            console.error('[TK Analytics] Failed to track storefront_quick_prompt_convert', e)
          }
        }
      } catch (err: any) {
        // Handle specific error types
        if (err.name === 'AbortError' || err.message?.includes('timeout')) {
          errorMessage = 'Request timed out. Please try again.'
        } else if (err.name === 'TypeError' && err.message?.includes('fetch')) {
          errorMessage = 'Network error. Please check your connection and try again.'
        } else {
          errorMessage = err.message || defaultErrorMessage
        }
        console.error('Error generating image:', err.message)
      } finally {
        // Always clean up skeleton/loading UI elements
        if (imageSkeleton) imageSkeleton.remove()
        if (loadingIndicator) loadingIndicator.remove()
      }
    }

    this.renderErrorMessage(errorMessage)

    return images
  }

  private renderErrorMessage(errorMessage: string): void {
    // Scope queries to this layer's fieldset to avoid affecting other layers
    const scopeElement = this.fieldset || document

    // Remove the error message if it exists within this layer's scope
    const errorElement = scopeElement.querySelector('.emtlkit--error-message')
    if (errorElement) {
      errorElement.remove()
    }

    if (!errorMessage) {
      return
    }

    const _errorElement = document.createElement('div')
    _errorElement.classList.add('emtlkit--error-message')
    _errorElement.innerHTML = `
          ${createSvgIcon(ERROR_ICON_PATH, 20, 'xmlns="http://www.w3.org/2000/svg" fill="currentColor"')}
          <span style="width: calc(100% - 24px);">${errorMessage}</span>
        `
    // Find the generate image wrapper within this layer's scope
    const imageAreaElement = scopeElement.querySelector('.emtlkit--generate-image-wrapper') as HTMLElement
    if (imageAreaElement) {
      imageAreaElement.appendChild(_errorElement)
    }
  }

  private clearAll(): void {
    // Show the generate button
    if (this.generateButton) {
      const buttonElement = this.generateButton.getElement()
      if (buttonElement) {
        buttonElement.style.display = ''
      }
    }

    // Clear suggestions
    if (this.suggestionList) {
      this.suggestionList.destroy()
      this.suggestionList = null
    }

    // Focus the textarea for new input
    const ids = this.layer ? getElementIds((this.layer as Layer).i || '') : null
    if (ids) {
      const textarea = document.getElementById(ids.textFieldId) as HTMLTextAreaElement | null
      textarea?.focus()
    }
  }

  /**
   * Handle option selection
   * @param selectedOption - The selected option
   */
  private async onSelectOption(selectedOption: TGeneratedImage | string): Promise<void> {
    if (typeof selectedOption !== 'string') {
      if (!this.fieldset || !this.layer) {
        console.error('Fieldset or layer not found')
        return
      }

      const objectUrl = selectedOption.originalSource
      const activator = this.activator
      const applyButton = this.suggestionList?.getApplyButton()
      const regenerateButton = this.suggestionList?.getRegenerateButton()

      if (applyButton) {
        applyButton.setLoading(true)
      }

      if (regenerateButton) {
        regenerateButton.setDisabled(true)
      }

      // For vector mode, apply SVG directly without opening the image editor modal
      if (this.mode === 'vector') {
        await this.applyVectorDirectly(objectUrl, selectedOption.filename)
        return
      }

      // For image mode, load the image and show the editor modal
      const imageElement = new Image()

      // Load the image
      imageElement.onload = async () => {
        // Extract layer dimensions from the layer data
        const {
          ds: { w: layerWidth, h: layerHeight, l: layerLeft, t: layerTop, r: layerRotation },
          osl,
        } = this.layer as Layer
        const transformerConfig = getTransformerConfig(osl)

        // Get mask config from layer's option sets
        const maskOption = getMaskOption(this.layer as Layer)
        const maskConfig = maskOption
          ? {
              src: maskOption.v,
              invert: false,
              globalCompositeOperation: 'destination-in' as const,
            }
          : undefined

        // Show the image editor modal
        await showImageEditorModal({
          objectUrl,
          imageElement,
          maskConfig,
          layerDimensions: {
            width: layerWidth,
            height: layerHeight,
            left: layerLeft,
            top: layerTop,
            rotation: layerRotation,
          },
          initialState: {
            zoom: 1,
            rotation: 0,
          },
          transformerConfig,
          onCancel: () => {
            URL.revokeObjectURL(objectUrl)
          },
          onReplaceImage: () => {
            URL.revokeObjectURL(objectUrl)
            setTimeout(() => {
              if (this.inlineMode) {
                this.focusInlineGenerator()
              } else {
                activator?.click()
              }
            }, 50)
          },
          onSubmit: async (editorState: KonvaEditorState, objectUrl: string, removedBackground?: boolean) => {
            let uploadResult = null

            // Convert the image URL to a File object
            const file = await urlToFile(objectUrl, selectedOption.filename)

            if (removedBackground) {
              uploadResult = {
                success: true,
                url: objectUrl,
              }
            } else {
              // Upload the image to the server
              uploadResult = await uploadImageToServer(file)
            }

            if (!uploadResult.success) {
              showErrorModal({
                title: 'Upload Error',
                message: uploadResult.error || 'Failed to upload image to server',
                onRetry: () => {
                  setTimeout(() => {
                    if (this.inlineMode) {
                      this.focusInlineGenerator()
                    } else {
                      activator?.click()
                    }
                  }, 50)
                },
              })
              URL.revokeObjectURL(objectUrl)
              return
            }

            // Process the image with the final URL and transform state
            await processUploadedImage({
              file,
              objectUrl,
              fieldset: this.fieldset as HTMLFieldSetElement,
              instance: this.instance as TailorKitProductPersonalizer,
              transforms: editorState,
              uploadedImageUrl: uploadResult.url,
              replaceImage: true,
              isGeneratedByAi: true,
              optionIdToReplace: this.optionIdToReplace,
            })

            // Find and switch to the appropriate view for this layer
            findViewAndSwitchTo(this.instance as TailorKitProductPersonalizer, this.fieldset as HTMLFieldSetElement)

            checkIfButtonIsDisabled(osl || [], this.fieldset as HTMLFieldSetElement, 3, 'image_generated_by_ai')
          },
        })

        this.clearAll()
      }

      imageElement.onerror = () => {
        console.error('Failed to load image for editor')
        URL.revokeObjectURL(objectUrl)
        showErrorModal({
          title: 'Image Error',
          message: 'Failed to load image for editing.',
          onRetry: () => {
            setTimeout(() => {
              activator?.click()
            }, 50)
          },
        })
      }

      imageElement.src = objectUrl
    }
  }

  /**
   * Apply generated vector SVG directly to the layer without opening modal
   * @param svgUrl - The SVG URL (CDN URL with filter already applied by backend)
   * @param filename - The filename for the vector
   */
  private async applyVectorDirectly(svgUrl: string, filename: string): Promise<void> {
    if (!this.fieldset || !this.layer || !this.instance) {
      console.error('Missing required data for vector application')
      return
    }

    const { osl } = this.layer as Layer

    try {
      // The backend already applies filter preset and uploads to Shopify CDN,
      // so we just use the returned URL directly without re-uploading
      const vectorFile = { name: filename || 'generated-vector.svg' } as File
      const emptyTransforms = {} as KonvaEditorState

      // Process the vector image with the URL returned from backend (filter already applied)
      await processUploadedImage({
        file: vectorFile,
        objectUrl: svgUrl,
        fieldset: this.fieldset,
        instance: this.instance,
        transforms: emptyTransforms,
        uploadedImageUrl: svgUrl,
        replaceImage: Boolean(this.optionIdToReplace),
        isGeneratedByAi: true,
        optionIdToReplace: this.optionIdToReplace,
      })

      // Find and switch to the appropriate view for this layer
      findViewAndSwitchTo(this.instance, this.fieldset)

      // Check and update button disabled state
      checkIfButtonIsDisabled(osl || [], this.fieldset, 3, 'image_generated_by_ai')
      this.clearAll()

      Transmitter.trigger('tailorkit-storefront-usage', { feature: 'AI_GEN_VECTOR' })
    } catch (error) {
      console.error('Failed to apply vector:', error)
      showErrorModal({
        title: 'Vector Error',
        message: 'Failed to apply the generated vector. Please try again.',
        onRetry: () => {
          if (this.inlineMode) {
            this.focusInlineGenerator()
          } else {
            this.activator?.click()
          }
        },
      })
    }
  }
}

export const handleGenerateImageWithAI = (
  target: HTMLElement,
  instance: TailorKitProductPersonalizer,
  replaceImage: boolean = false,
  optionIdToReplace: string = ''
) => {
  const fieldset = target.closest('fieldset') as HTMLFieldSetElement
  if (!fieldset) return

  const inlineContainer
    = (target.closest('.emtlkit--generate-image-with-ai') as HTMLElement)
    || (fieldset.querySelector('.emtlkit--generate-image-with-ai[data-inline-ai-generator="true"]') as HTMLElement | null)

  if (inlineContainer) {
    const handler = new GenerateImageHandler(inlineContainer, instance, replaceImage, optionIdToReplace)
    handler.mountInlineGenerator()
    return
  }

  const activator
    = (target.closest('.emtlkit-button.ai-generate') as HTMLElement)
    || (fieldset.querySelector('.emtlkit-button.ai-generate') as HTMLElement)

  if (!activator) return

  // const handler = new GenerateImageHandler(activator, instance, replaceImage, optionIdToReplace)
  // handler.handleGenerate()
}

function getElementIds(layerId: string) {
  return {
    containerId: `emtlkit--container-${layerId}`,
    textFieldContainerId: `emtlkit--text-field-container-${layerId}`,
    textFieldId: `emtlkit--generate-image-textarea-${layerId}`,
    referenceSelectContainerId: `emtlkit--reference-select-container-${layerId}`,
    referenceSelectBtnId: `emtlkit--reference-select-btn-${layerId}`,
    referenceStatusId: `emtlkit--reference-status-${layerId}`,
    aspectRatioBtnId: `emtlkit--aspect-ratio-btn-${layerId}`,
    ratioOptionsContainerId: `emtlkit--aspect-ratio-options-container-${layerId}`,
    styleOptionsContainerId: `emtlkit--style-options-container-${layerId}`,
    styleBtnId: `emtlkit--style-btn-${layerId}`,
    generateButtonContainerId: `emtlkit--generate-text-btn-container-${layerId}`,
    generateButtonId: `emtlkit--generate-text-btn-${layerId}`,
  }
}
