/**
 * Orchestrates complete template creation pipeline with context analysis, style mapping, and AI generation.
 */

import type { ChatInvoker } from '../../services/ProductIntentAnalyzer'
import type { TemplateContextAnalyze } from '../context/ContextAnalyzer'
import { ContextAnalyzer, DEFAULT_RESOLUTION } from '../context/ContextAnalyzer'
import { CanvasStyleEngine, type StyleMapping } from './CanvasStyleEngine'
import { ProductCanvasAdapter, type ProductCanvasComposition } from './ProductCanvasAdapter'
import type { AssistantResponse } from '~/libs/langchain/assistant.service'
import { ELayerType } from '~/types/psd'
import type { TextSettings, ImageSettings } from '~/types/psd'
import { uuid } from '~/utils/uuid'
import { buildImagePrompt } from '~/libs/langchain/agents/templates/utils/imagePromptBuilder'
import type { MEASUREMENT_UNIT } from '~/constants/measurement-units'
import type { RESOLUTION } from '~/constants/resolution'
import type { LayerDocument } from '~/models/Layer.server'
import { getShopData } from '~/models/Shop.server'
import { EmitStatusService } from '../../services/EmitStatusService'
import { ImageService } from '../../services/ImageService'
import type { SupervisorState } from '~/libs/langchain/supervisor'
import { generateTemplatePreviewUrl } from '~/utils/generateTemplatePreview.server'
import { LANGUAGE_SUPPORT_MESSAGE } from '~/libs/langchain/constant'

/** Complete template data structure for database persistence with layers and metadata. */
export interface TemplateData {
  /** Template display name */
  name: string

  /** Canvas dimensions and specifications */
  dimension: {
    /** Canvas width in specified units */
    width: number
    /** Canvas height in specified units */
    height: number
    /** Unit of measurement for dimensions */
    measurementUnit: MEASUREMENT_UNIT
    /** Print resolution specification */
    resolution: RESOLUTION
  }

  /** Array of template layers with styling and positioning */
  layers: Partial<LayerDocument>[]

  /** Optional preview image URL */
  previewUrl?: string

  /** Template generation metadata */
  metadata: {
    /** ISO timestamp of when template was generated by AI */
    generatedByAIAssistantAt: string
  }
}

type UploadedImage = {
  alt: string
  image: {
    originalSrc: string
    width: number
    height: number
  }
}

interface LayerPosition {
  x: number
  y: number
  width: number
  height: number
}

interface LayerImageData {
  _id: string
  src: string
  imageName: string
  width: number
  height: number
  generativeOptions?: {
    imageType?: string
    prompt?: string
    imageStyle?: string
    aspectRatio?: string
  }
}

type TLayer = {
  _id: string
  type: ELayerType
  label: string
  settings?: TextSettings | ImageSettings
  position: LayerPosition
  zIndex: number
  visible: boolean
  imagePrompt?: string
  image?: LayerImageData
}

/** Orchestrator that coordinates template creation through analysis, styling, adaptation, and AI generation. */
export class TemplateComposer {
  /** Context analyzer for parsing user prompts and extracting design intent */
  private contextAnalyzer: ContextAnalyzer

  /** Style engine for converting contexts into abstract canvas elements */
  private canvasStyleEngine: CanvasStyleEngine

  /** Product adapter for applying production constraints to elements */
  private productCanvasAdapter: ProductCanvasAdapter

  /** Status service for real-time progress updates */
  private emitStatusService: EmitStatusService

  /** Image service for AI image generation and management */
  private imageService: ImageService

  /** Creates TemplateComposer with AI services for complete template generation workflow. */
  constructor(private chatInvoker: ChatInvoker) {
    this.contextAnalyzer = new ContextAnalyzer(chatInvoker)
    this.canvasStyleEngine = new CanvasStyleEngine(chatInvoker)
    this.productCanvasAdapter = new ProductCanvasAdapter(chatInvoker)
    this.emitStatusService = new EmitStatusService(chatInvoker)
    this.imageService = new ImageService(chatInvoker)
  }

  private normalizeType(value: unknown): ELayerType {
    const v = String(value ?? '').toLowerCase()
    return v === ELayerType.TEXT || v === 'text' ? ELayerType.TEXT : ELayerType.IMAGE
  }

  private selectLabel(el: ProductCanvasComposition['elements'][number]): string {
    // Prefer label from model if present; otherwise titleize ID as fallback
    const labelFromModel = el && typeof el === 'object' && 'label' in el ? (el as { label?: string }).label : undefined
    if (labelFromModel && typeof labelFromModel === 'string' && labelFromModel.trim()) {
      return labelFromModel.trim()
    }
    const id = el?.id || ''
    return (
      id
        .replace(/[_-]+/g, ' ')
        .replace(/\s+/g, ' ')
        .trim()
        .replace(/\b\w/g, c => c.toUpperCase()) || 'Layer'
    )
  }

  private mergeTextSettingsFromStyle(
    elementId: string | undefined,
    adapterSettings: any,
    styleMapping: StyleMapping
  ): Partial<TextSettings> {
    const styleEl = styleMapping.elements.find(e => e.id === elementId)
    const s = { ...(styleEl?.styleSettings || {}), ...(adapterSettings || {}) }

    const merged: Partial<TextSettings> = {
      storefrontLabel: s.storefrontLabel,
      content: s.content,
      fontFamily: s.fontFamily,
      fontSize: s.fontSize,
      textStyle: typeof s.textStyle === 'string' ? s.textStyle : undefined,
      textColor: s.textColor,
      textAlign: s.textAlign,
      verticalAlign: typeof s.verticalAlign === 'string' ? s.verticalAlign : undefined,
      styleCase: typeof s.styleCase === 'string' ? s.styleCase : undefined,
      strokeColor: typeof s.strokeColor === 'string' ? s.strokeColor : undefined,
      strokeWeight: typeof s.strokeWeight === 'number' ? s.strokeWeight : undefined,
      neonMode: typeof s.neonMode === 'string' ? s.neonMode : 'none',
      neonIntensity: typeof s.neonIntensity === 'number' ? s.neonIntensity : undefined,
      autoFitToContainer: typeof s.autoFitToContainer === 'boolean' ? s.autoFitToContainer : true,
      textShape: s.textShape,
      placeholder: typeof s.placeholder === 'string' ? s.placeholder : undefined,
      required: typeof s.required === 'boolean' ? s.required : undefined,
      textCreatedBy: typeof s.textCreatedBy === 'string' ? s.textCreatedBy : undefined,
      characterLimit: typeof s.characterLimit === 'number' ? s.characterLimit : undefined,
      notesForCustomers: typeof s.notesForCustomers === 'string' ? s.notesForCustomers : undefined,
      generateTextWithAI: typeof s.generateTextWithAI === 'boolean' ? s.generateTextWithAI : undefined,
      curvePeaks: typeof s.curvePeaks === 'number' ? s.curvePeaks : undefined,
      curveBend: typeof s.curveBend === 'number' ? s.curveBend : undefined,
      circleStartAngle: typeof s.circleStartAngle === 'number' ? s.circleStartAngle : undefined,
      circleEndAngle: typeof s.circleEndAngle === 'number' ? s.circleEndAngle : undefined,
    }

    return Object.fromEntries(Object.entries(merged).filter(([, v]) => v !== undefined)) as Partial<TextSettings>
  }

  private mapElementToLayer(el: ProductCanvasComposition['elements'][number], styleMapping: StyleMapping) {
    const normalizedType = this.normalizeType(el.type)
    const labelFromId = this.selectLabel(el)

    const base: TLayer = {
      _id: uuid(),
      type: normalizedType,
      label: labelFromId,
      position: {
        x: Math.max(0, el.transform.x),
        y: Math.max(0, el.transform.y),
        width: Math.max(1, el.transform.width),
        height: Math.max(1, el.transform.height),
      },
      zIndex: el.layering?.zIndex ?? 1,
      visible: true,
      imagePrompt: el.settings?.imagePrompt,
      settings: el.settings,
    }

    if (normalizedType === ELayerType.TEXT) {
      const settings = this.mergeTextSettingsFromStyle(el.id, el.settings, styleMapping)
      return { ...base, settings }
    }

    delete el.settings?.imagePrompt
    delete el.settings?.imageStyle
    delete el.settings?.imageType
    const imageSettings: Partial<ImageSettings> = { ...el.settings } as ImageSettings
    const cleanedImg = Object.fromEntries(Object.entries(imageSettings).filter(([, v]) => v !== undefined))
    return { ...base, settings: Object.keys(cleanedImg).length ? (cleanedImg as any) : undefined }
  }

  private buildTemplateContext(
    context: TemplateContextAnalyze,
    templateName: string,
    cardId: string,
    userMessage: string
  ): string {
    return `TEMPLATE ANALYSIS DATA:
Respond briefly in a warm, enthusiastic tone, expressing delight in helping the user create their template.
Then create a template card: [TEMPLATE_CARD:${cardId}] (${templateName})'

Do NOT include any TEMPLATE_DATA or JSON in your response. Just natural text + the template card marker.
Use the user's message to determine the language of the response: ${userMessage}.
${LANGUAGE_SUPPORT_MESSAGE}
`
  }

  /** Creates complete template from prompt through AI pipeline with streaming status updates. */
  async createTemplate(args: {
    prompt: string
    context: SupervisorState['context']
    onChunk?: (chunk: string) => void
    conversationHistory?: AssistantResponse[]
  }): Promise<string> {
    const { prompt, conversationHistory, onChunk, context } = args
    try {
      onChunk && (await this.emitStatusService.emitStatus(onChunk, 'i-m-figuring-out-your-idea'))
      const templateContext: TemplateContextAnalyze = await this.contextAnalyzer.analyzeContext(
        prompt,
        conversationHistory
      )

      onChunk && (await this.emitStatusService.emitStatus(onChunk, 'picking-the-right-colors-and-style'))
      const styleMapping: StyleMapping = await this.canvasStyleEngine.mapStyleToCanvasElements(templateContext.style)

      onChunk && (await this.emitStatusService.emitStatus(onChunk, 'trying-that-style-on-your-product'))
      const productComposition: ProductCanvasComposition = await this.productCanvasAdapter.adaptStyleToProduct(
        styleMapping,
        templateContext.product
      )

      onChunk && (await this.emitStatusService.emitStatus(onChunk, 'almost-done-putting-the-final-touches'))

      // Build TemplateData-compatible payload like TemplateComposer
      const templateName = templateContext.templateName || `AI Template - ${new Date().toLocaleDateString()}`
      const { width, height, measurementUnit, resolution } = productComposition.canvasProperties.dimension
      const dimension = {
        width,
        height,
        measurementUnit,
        resolution: resolution || DEFAULT_RESOLUTION,
      }
      const cardId = `template_${uuid()}`

      // Map composition elements to CompositionPlan layers (no hard-coded labels)
      const mappedLayers = productComposition.elements.map(el => this.mapElementToLayer(el, styleMapping))

      // Generate separate images for each IMAGE layer
      const imageLayers = mappedLayers.filter(l => l.type === ELayerType.IMAGE)
      if (imageLayers.length > 0) {
        // Build enriched prompts per layer
        const prompts = imageLayers.map(layer =>
          buildImagePrompt({
            basePrompt: layer.imagePrompt || '',
            layer: { ...layer, id: layer._id },
            templateContext,
            styleMapping,
          })
        )

        const optimizedPrompts: string[] = prompts

        const shopDomain = context?.shopDomain || ''
        const shopData = await getShopData(shopDomain)
        const hardenedPrompts = optimizedPrompts.map(p => `${p.trim()}`)

        const { filesPerLayer, imageLayers: generatedImageLayers } = await this.imageService.generateAndApplyImage({
          onChunk,
          shopData,
          imageLayers: imageLayers.map(l => ({
            _id: l._id,
            label: l.label,
            imagePrompt: l.image?.generativeOptions?.prompt || l.imagePrompt || '',
            imageType: l.settings?.imageType || '',
            imageStyle: l.image?.generativeOptions?.imageStyle || l.settings?.imageStyle || '',
            aspectRatio: l.image?.generativeOptions?.aspectRatio || l.settings?.aspectRatio || '',
            imageWidth: l.position.width,
            imageHeight: l.position.height,
          })),
          optimizedPrompts,
          context,
          userMessage: prompt,
        })

        imageLayers.forEach((layer, idx) => {
          const file = filesPerLayer[idx]
          const generatedImageLayer = generatedImageLayers[idx]

          if (file && typeof file === 'object' && 'alt' in file && 'image' in file) {
            const uploadedFile = file as UploadedImage
            const gPrompt = hardenedPrompts[idx] || prompts[idx]
            layer.image = {
              _id: uuid(),
              src: uploadedFile.image?.originalSrc || '',
              imageName: uploadedFile.alt || '',
              width: uploadedFile.image?.width || 0,
              height: uploadedFile.image?.height || 0,
              generativeOptions: {
                ...(layer.image?.generativeOptions || {}),
                prompt: gPrompt,
                imageType: generatedImageLayer.imageType || layer.settings?.imageType || '',
                imageStyle: generatedImageLayer.imageStyle || layer.settings?.imageStyle || '',
                aspectRatio: generatedImageLayer.aspectRatio || layer.settings?.aspectRatio || '',
              },
            }
          }
        })
      }

      const layers = mappedLayers
        .sort((a, b) => a.zIndex - b.zIndex)
        .map(l => ({
          _id: uuid(),
          type: l.type,
          label: l.label,
          settings: l.settings,
          image: l.image,
          width: l.position.width,
          height: l.position.height,
          left: l.position.x,
          top: l.position.y,
          visible: l.visible ?? true,
          isCreatedByAIAssistant: true,
        }))

      // Generate preview image and upload to S3 to obtain previewUrl
      const shopDomain = context?.shopDomain || ''
      const previewUrl: string = await generateTemplatePreviewUrl({
        dimension,
        layers: layers as any,
        shopDomain,
      }).catch(e => (console.warn('Failed to generate preview image:', e), ''))

      const templateData: TemplateData & { cardId: string; ctaButton: { text: string } } = {
        name: templateName,
        dimension,
        previewUrl,
        layers,
        cardId,
        metadata: { generatedByAIAssistantAt: new Date().toISOString() },
        ctaButton: { text: 'create-template' },
      }

      // Emit COMPLETE status like the legacy TemplateComposer
      if (typeof onChunk === 'function') {
        onChunk('[STATUS][COMPLETE][/STATUS]')
      }

      // Generate natural language summary like legacy composer
      const contextMessage = this.buildTemplateContext(templateContext as any, templateName, cardId, prompt)
      const aiResponse = await this.emitStatusService.generateAIResponse({
        query: prompt,
        contextMessage,
        isStreaming: typeof onChunk === 'function',
        onChunk,
      })

      const chunk = `\nTEMPLATE_DATA:${JSON.stringify(templateData)}`
      onChunk && onChunk(chunk)
      return aiResponse + chunk
    } catch (error: any) {
      console.error('🔥 Error creating template:', error)
      const friendly = await this.emitStatusService.generateUserFriendlyError(error, 'Create template')
      const msg = `\n${friendly}`
      if (typeof onChunk === 'function') {
        onChunk(msg)
      }
      return msg
    }
  }
}
